### ISSUE TITLE
Regex in router specmatic considering multiple endpoints which are not actual endpoints present in service.

### ISSUE THREAD

**Issue by rajsavsani** [specmatic/specmatic#1033]
while i adding regex validation in route i getting list of endpoint that are not present in service at all.

for example if i have route like this service/abc/:test(\\d+)/qrt/:xyz([0-9a-f]{24})

this will creating endpoint list like 

service/abc/qrt
service/abc/:test
and so on.

**Comment by harikrishnan83** [comment]
hello @rajsavsani , thanks for reaching out. Can you please share more context?
1. Where are seeing this behaviour? While running tests or while running stubs
2. Can you please give us a sample API spec which we can use to reproduce the issue
3. Also rough list of steps to reproduce the problem you are facing

**Comment by harikrishnan83** [comment]
@rajsavsani this issue has been fixed in [node release 1.3.11](https://www.npmjs.com/package/specmatic/v/1.3.11). Please check. Closing this issue for now. Please feel free to re-open if necessary.
