### ISSUE TITLE
XML support for namespaces

### ISSUE THREAD

**Issue by joelrosario** [specmatic/specmatic#105]
**Is your feature request related to a problem? Please describe.**
XML namespace prefixes can change, but this is acceptable. Parsers are supposed to use the actual namespaces referred to by the prefix.

For example,

```xml
<ns1:data xmlns:ns1="http://example.com/data"><name>Jane Doe</name></ns1:data>
```

is supposed to be equivalent to:

```xml
<ns2:data xmlns:ns2="http://example.com/data"><name>Jane Doe</name></ns2:data>
```

since the actual namespace value is the same in both.

WSDL codeine tools (such as jaxby) may generate a different namespace prefix for various XML data structures in a given WSDL file each time it is run. But Qontract treats the namespace prefix literally. So when codegen runs and a different namespace prefix is generated, even if the namespace value is the same, Qontract treats it as a different node name.

So in the above example, if the contract contained:

```gherkin
Given type <ns1:data xmlns:ns1="http://example.com/data"><name>(string)</name></ns1:data>
```

And the value in the payload is:

```xml
<ns2:data xmlns:ns2="http://example.com/data"><name>Jane Doe</name></ns2:data>
```

which might happen because the namespace changed when the code was generated, Qontract will consider them different, and return an error.

**Describe the solution you'd like**

Qontract should consider this xml type:

```xml
<ns1:data xmlns:ns1="http://example.com/data"><name>(string)</name></ns1:data>
```

to match this xml value:

```xml
<ns2:data xmlns:ns2="http://example.com/data"><name>Jane Doe</name></ns2:data>
```

given that the actual namespace value in both is the same, even though the namespace prefixes are different.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jaydeepk** [comment]
We will  discuss this internally and decide how we want to take this forward.

**Comment by joelrosario** [comment]
Given the support for OpenAPI that we have now and given where SOAP support has evolved, closing this for now. We'll open a new ticket if needed later on.
