### ISSUE TITLE
The named examples are not being picked up correctly when there is no response example for 204 responses.

### ISSUE THREAD

**Issue by yogeshnikam671** [specmatic/specmatic#1063]
**Description**
When specifying 204 status code in OpenAPI spec, we do not specify the response schema/example since 204 always returns `No-content` as the response.
Although, we can specify the request example. 
 
**Expected behavior**
I would want specmatic to make use of the request example while running the contract test.

**Actual behaviour**
Specmatic does not make use of the request example and generates random values for the contract test.

**Steps to reproduce**
1. Implement a simple API which returns 204 and adheres to following schema -
```
openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /api/nocontent:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
            examples:
              204_OK:
                value: "hibob"
      responses:
        204:
          description: No content 
```
2. Run contract test using specmatic
3. Observe that, the value "hibob" is not getting used by specmatic while hitting this endpoint during the contract test.

**System Information:**
 - Specmatic version: 1.3.10
 - JDK version: 17

**Comment by joelrosario** [comment]
Thanks for reporting this @yogeshnikam671. This will be addressed in the next release (2.0.16).
