### ISSUE TITLE
Specmatic unable to parse valid DateTime

### ISSUE THREAD

**Issue by noelmccrory** [specmatic/specmatic#1078]
**Description**
I am running Contract Tests with Specmatic against a Spring Boot app. My OpenAPI spec has the field defined as:

```
        createDatetime:
          type: string
          format: date-time
```

In my Java model the field is:

`private OffsetDateTime createDatetime;`

When my contract tests run, the API produces a response of `"createDatetime": "2024-04-25T09:06:26.572577Z",` which is a valid ISO 8601 format.

However, Specmatic produces the following error:

```
	  >> RESPONSE.BODY.createDatetime
	  
	     Error: Text '2024-04-25T09:06:26.572577Z' could not be parsed at index 19
```

It doesn't seem to like the `Z`.

**Steps to reproduce**
See Description

**Expected behavior**
Specmatic should accept `2024-04-25T09:06:26.572577Z` as a valid datetime.

**Screenshots**
N/A

**System Information:**
 - Specmatic version: 1.3.11
 - JDK version: 21

**Additional context**
Related issue - https://github.com/znsio/specmatic/issues/721

**Comment by burdeamit** [comment]
Hello @noelmccrory, 
Thanks for reporting this date issue. We will have a look at it and get back to you.

**Comment by harikrishnan83** [comment]
@noelmccrory We have fixed this issue and the same should be available in our upcoming release. cc @burdeamit @yogeshnikam671
