### ISSUE TITLE
Custom header object?

### ISSUE THREAD

**Issue by stoconnor** [specmatic/specmatic#108]
Is it possible to define a custom header object in the Qontract gherkin?

For example documentation shows the example for a Cookie header:
`And request-header Cookie (string)`

What I'm looking to achieve:
`And request-header my-object {"key1": "val1"}`

**Comment by joelrosario** [comment]
Are you looking for something like this:

```gherkin
# filename: header_test.qontract
Feature: Header test
  Scenario: Header value has JSON format
    Given type KeyValuePair
    | token | (string) |
    When GET /
    And request-header X-FormattedHeader (KeyValuePair)
    Then status 200
    And response-body (string)
```

Then open two shell tabs.

In tab 1:
```bash
$ qontract stub header_test.qontract
Loading header_test.qontract
Stub server is running on http://0.0.0.0:9000. Ctrl + C to stop.
```

In tab 2:
```bash
$ curl -H 'X-FormattedHeader: {"token": "123abc"}' http://localhost:9000/
YLBKG
```

**Comment by stoconnor** [comment]
Thanks @joelrosario, I copied in your feature and scenario, however I get the following error (running with a Java Spring Boot app with JUnit5)

`java.lang.AssertionError: Testing scenario "Header value has JSON format"
Error: Header value '{
    "token": "AGFYT"
}' contains illegal character '
' (code 10)`

**Comment by joelrosario** [comment]
Hey @stoconnor could you post the code that gives you that error please.

**Comment by stoconnor** [comment]
Very simple test setup and Feature file you provided. Test file:

```java
package com.soc.qontract;

import com.soc.qontract.MainApplication;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import run.qontract.test.QontractJUnitSupport;

import java.io.File;

public class SocServiceContractTests extends QontractJUnitSupport {
  private static ConfigurableApplicationContext context;

  @BeforeAll
  public static void setUp() {
    File contract = new File("src/main/header_test.qontract");
    System.setProperty("contractPaths", contract.getAbsolutePath());
    System.setProperty("host", "localhost");
    System.setProperty("port", "8080");

    //Optional
    context = SpringApplication.run(MainApplication.class);
  }

  @AfterAll
  public static void tearDown() {
    //Optional
    context.stop();
  }
}
```

Feature file:
```gherkin
# filename: header_test.qontract
Feature: Header test
  Scenario: Header value has JSON format
    Given type KeyValuePair
    | token | (string) |
    When GET /
    And request-header X-FormattedHeader (KeyValuePair)
    Then status 200
    And response-body (string)
```

Error:
```
java.lang.AssertionError: Testing scenario "Header value has JSON format"
Error: Header value '{
    "token": "RNEFM"
}' contains illegal character ' ' (code 10)
```

Is it possible it's related to this line of code that's adding whitespace to the JSON header?  :
https://github.com/qontract/qontract/blob/a76ff0bdd5d88da0d3a2f6743fbcbf448565dfb1/core/src/main/kotlin/run/qontract/core/Feature.kt#L349

**Comment by joelrosario** [comment]
@stoconnor This line splits a string up into pieces, and does not add spaces.

However, your intuition that something is adding spaces is probably right. In fact if code 10 refers to ASCII code 10, then that would be the new line character '\n'. The JSON deserialiser does generate a readable multiline json string, and my current guess is that this may not be playing well with the HTTP client library. I'll take a closer look a little later in the day.

**Comment by joelrosario** [comment]
Hey @stoconnor , I've tested and confirmed my hypothesis.

In summary, the Qontract language supports defining custom header formats, and it can certainly be used in stub mode.

However, if we provide a JSON format for a header value, Qontract generates a multiline header value. When the HTTP client (ktor client) encounters the multiline header, it throws an exception. As a result, Qontract is unable to run contract tests for a scenario with such a header value definition.

I have [raised a bug report for this](https://github.com/qontract/qontract/issues/116).

I believe that should serve as both an answer to your question and a resolution for this ticket.

I'm closing it now, but please feel free to reopen it if you have any followup questions on this topic.

**Comment by stoconnor** [comment]
Thanks Joel!
