### ISSUE TITLE
Qontract test command through qontract.json

### ISSUE THREAD

**Issue by sahilaug** [specmatic/specmatic#112]
**Description**
Contract test command does'nt work when the qontract path is given in the qontract.json. The following commands works fine.
`qontract test tests_new/contract/getRoom.qontract --host=localhost --port=5000`
But gives an error if the qontract path is ommitted from the command and added to qontract.json instead.

**Steps to reproduce**
1. add the path to qontract.json like this
`"test": [
          "tests_new/contract/getRoom.qontract"
 ]`
2. Run this command: `qontract test --host=localhost --port=5000`

**Expected behavior**
getRoom.qontract should run in test mode
instead it gives an error:
`Missing required parameter: '<path>'`

**System Information:**
- qontract version : 0.18.0

**Comment by jaydeepk** [comment]
Hi @sahilaug 
We now have a Specmatic.json file in which you can point to local files (provided their full path is specified).
Closing this for now, please do feel to reopen this is needed.
