### ISSUE TITLE
Qontract.json file to support wildcard paths

### ISSUE THREAD

**Issue by sahilaug** [specmatic/specmatic#113]
**Is your feature request related to a problem? Please describe.**
Too many contracts is making the qontract.json file to bloat
`
"stub": [
          "tests_new/contract/external/vidyo/room/findRoom.qontract",
          "tests_new/contract/external/vidyo/room/createRoom.qontract",
          "tests_new/contract/external/idam/sendOTP.qontract",
          "tests_new/contract/external/idam/validateOTP.qontract",
          "tests_new/contract/external/vidyo/room/createScheduledRoom.qontract",
          "tests_new/contract/external/vidyo/room/createRoomPIN.qontract",
          "tests_new/contract/getRoom.qontract"
        ]
`
We are expecting this number to go to hundreds.

**Describe the solution you'd like**
Instead of listing the paths of all the qontract files, user should be able to provide wildcards eg. test: `[contracts/**/*.qontract]`

**Comment by jaydeepk** [comment]
Good suggestion, we need to discuss and decide if want to implement this.
