### ISSUE TITLE
A way to dynamically set examples in a contract

### ISSUE THREAD

**Issue by sahilaug** [specmatic/specmatic#114]
**Is your feature request related to a problem? Please describe.**
After a login api call, I get a jwt token that is needed for the rest of the contract tests. I can get the jwp through a script or a karate test, but I need a way to make sure that rest of my contracts use this jwt token while running

**Describe the solution you'd like**
like we have loadDynamicEpectation api to dynamically change the stub, we should have a loadDynamicQontractExample : which can dyncamically load the value of the example through a script.

**Describe alternatives you've considered**
Instead of altering the qontract, we can have a concept of variables which can be used inside a qontract file, but still we would need a way to dynamicallyChange that variable.

**Comment by jaydeepk** [comment]
This looks like a good suggestion.We need to discuss it internally and decide if it's worth pursuing.
