### ISSUE TITLE
JSON format for header value results in IllegalHeaderValueException in test mode

### ISSUE THREAD

**Issue by joelrosario** [specmatic/specmatic#116]
**Description**
If a JSON format is specified for a header value, Qontract cannot successfully generate a header value when running a test.

JSON values are generated using a pretty printer, so any JSON value takes up at least 3 lines. When the value of such a header is generated for the purpose of running a test, the http client throws an error because it sees a multilingual string. A header value can consist of only a single line.

**Steps to reproduce**
1. Create a contract with this content:

```gherkin
# filename: header_test.qontract
Feature: Header test
  Scenario: Header value has JSON format
    Given type KeyValuePair
    | token | (string) |
    When GET /
    And request-header X-FormattedHeader (KeyValuePair)
    Then status 200
    And response-body (string)
```

2. Run it as a stub (`qontract stub header_test.qontract`).
3. Run it as a test against the stub from line 2 (`qontract test header_test.qontract`) to see the error.

You can do the same with the following contract as well:

```gherkin
# filename: header_test.qontract
Feature: Header test
  Scenario: Header value has JSON format
    Given type KeyValuePair {"token": "(string)"}
    When GET /
    And request-header X-FormattedHeader (KeyValuePair)
    Then status 200
    And response-body (string)
```

**Expected behavior**
When a JSON format is specified for any reason as part of a value that cannot have more than one line:
1. It must be serialised without pretty printing,
2. If there are multiple lines as a result, the error message should clearly state the cause of failure to be multiple lines.

**Screenshots**
n/a

**System Information:**
 - OS & version: macOS Catalina 10.15.7
 - Browser & version: Safari
 - Qontract version: 0.19.1
 - JDK version: 8

**Additional context**
n/a

**Comment by jaydeepk** [comment]
Hi @joelrosario , I tried this out locally and it seems to be working with the current specmatic version (0.70.0)
```
% specmatic test header.qontract
Endpoints API not found, cannot calculate actual coverage

--------------------
  Request to http://localhost:9000 at 2023-6-16 0:39:55.635
    GET /
    X-FormattedHeader: {"token":"RJKGM"}
    Accept-Charset: UTF-8
    Accept: */*



  Response at 2023-6-16 0:39:55.635
    200 OK
    Vary: Origin
    X-Specmatic-Result: success
    X-Specmatic-Type: random
    Content-Length: 5
    Content-Type: text/plain
    Connection: keep-alive

    DILQK

 Scenario: GET / -> 200 SUCCESSFUL


|--------------------------------------------|
| API COVERAGE SUMMARY                       |
|--------------------------------------------|
|  status | path | method | response | count |
|---------|---|--------|----------|-------|
| covered | / |    GET |      200 |     1 |
|--------------------------------------------|
| 1 / 1 APIs covered                         |
|--------------------------------------------|
Tests run: 1, Successes: 1, Failures: 0, Errors: 0
```

**Comment by joelrosario** [comment]
@jaydeepk yes, thanks, this was recently fixed.
