### ISSUE TITLE
Specmatic is expecting new non-required field in example response

### ISSUE THREAD

**Issue by noelmccrory** [specmatic/specmatic#1206]
**Description**
I have an existing API Specification being used by Specmatic for Contract Tests which use examples defined in the API Spec. I am looking to add a new optional field to the response of one of the endpoints, so I've added the new field to the model schema:

```
        newField:
          type: string
          readOnly: true
```

However, when I run the Contract Tests on my existing service which has not yet been updated to return the new field, I get the following error message:

```
  	  >> RESPONSE.BODY.newField
	  
  	     Value mismatch: key newfield was missing
```

If I add `nullable: true` to `newField`, then it works, so it looks like Specmatic is treating this as a required field in the response if it's not nullable? But my understanding is that optionality and nullability are two different things.

**System Information:**
 - OS & version: MacOS 14.5
 - Specmatic version: 1.3.39
 - JDK version: 21

**Comment by noelmccrory** [comment]
Closing this, as I've made a mistake. Will open new issue after further discovery.

**Comment by yogeshnikam671** [comment]
Thanks. Please do open an issue when you have the details.
