### ISSUE TITLE
How do i contact Specmatic to get private beta access to Kafka stub server?

### ISSUE THREAD

**Issue by tomknee-accelins** [specmatic/specmatic#1211]
-------------- 👆 Click "Preview"!

Issues on GitHub are intended to be related to problems with the library itself
and feature requests so we recommend not using this medium to ask them here 😁.

---

## ❓ Support Forums

For questions related to using the library, please ask them on  https://github.com/znsio/specmatic/discussions. You can also reach us through  https://specmatic.io/contact-us.

- Documentation: https://specmatic.io/documentation.html

**Comment by nashjain** [comment]
Hi Thomas,

Good news is we are out of beta into a fully supported paid offering. If you want to try them out, we've released the trail version publicly. There are couple of approaches you can use:

- Use our [Docker images](https://hub.docker.com/r/znsio/specmatic-kafka-trial)
- Use the specmatic-kafka jar similar to the [sample project](https://specmatic.io/documentation/sample_projects.html#kafka)

Hope this help.
