### ISSUE TITLE
How to add exclude specific api methods in Coverage Report?

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#1215]
In Specmatic Coverage, I want to exclude some GET requests of an API but still test the POST requests. How can I achieve this?

**Comment by harikrishnan83** [comment]
Thanks @barath121 for reaching out. I will get back to you shortly on this.

**Comment by harikrishnan83** [comment]
@barath121 Please take a look at this [documentation on filters](https://specmatic.io/documentation/contract_tests.html#filtering-tests-by-http-method-name). Hope this helps. Do let us know if you have any questions on this. Thanks.

**Comment by barath121** [comment]
@harikrishnan83 Will this also skip it form API coverage report?

**Comment by harikrishnan83** [comment]
hello @barath121 , no this will not skip it from the API Coverage. The purpose of the coverage report and associated minimum coverage limits is to make sure that we have constant feedback that some aspects of the spec are not being fully tested, which included filtered out API endpoints and operations. Hope this clarifies. Thanks.

**Comment by harikrishnan83** [comment]
@barath121  To remove an endpoint from coverage that an be achieved through API Coverage Report section in `specmatic.yaml`. Here is the relevant [documentation](https://specmatic.io/documentation/configuration.html#api-coverage-report). Closing this issue, as per our discussion. Please feel free to re-open if you have any questions on this. Thanks.

**Comment by GagandeepSharma060** [comment]
Hi @harikrishnan83 , the filters thing that you mentioned. Is it also possible if I am not using junit/java for my tests and if i just have the yaml files -> mention it in the specmatic.json and then run it through command line. I tried multiple ways but was not able to do so
