### ISSUE TITLE
Created json files and the contract file are not compatible

### ISSUE THREAD

**Issue by GagandeepSharma060** [specmatic/specmatic#1366]
I have a UI and an API, the API i am trying to record using the proxy server , and the localhost url provided to me by the specmatic ,
I run some of my automation tests and some json files are generated by the proxy along with a contract file, but when I start the stub server with the json file then there is an error saying that some of the stub files are not compatible with the contract, even though both the files were created by specmatic from the same endpoints

**Comment by pranavgawri** [comment]
Hi @GagandeepSharma060,

Thanks for reporting this issue with stub compatibility. While in our test environment the stubs generated by the proxy server work seamlessly with the contracts, I understand you're seeing compatibility errors.

To help us investigate this thoroughly, could you please share:

1. The contract file generated by the proxy
2. The JSON stub files that are showing compatibility errors
3. The exact error message you're receiving when starting the stub server
4. The commands you're using to:
   - Start the proxy server
   - Generate the contracts/stubs
   - Start the stub server

This will help us replicate the issue at our end.

Looking forward to resolve this!

Thanks,
Pranav

**Comment by pranavgawri** [comment]
Hi @GagandeepSharma060 ,

In case, you still facing this issue, I would request to share additional info as requested in the message above. 

Thanks, 
Pranav

**Comment by pranavgawri** [comment]
Hi @GagandeepSharma060 ,

Hope you are doing well. If in case this is not an issue anymore I would request you to please close it. 
In case you are still facing the problem then can you please share the specs with us, as we are unable to replicate it at our end.

Looking forward to hear from you.

Thanks,
Pranav

**Comment by GagandeepSharma060** [comment]
Yes @pranavgawri , we can close this. Apologies for the delayed response

**Comment by pranavgawri** [comment]
Thanks @GagandeepSharma060. Closing it.
