### ISSUE TITLE
Boolean with value always true

### ISSUE THREAD

**Issue by GagandeepSharma060** [specmatic/specmatic#1424]
Hi team,

Another question in the list of manu questions that I have asked  🥲
I just wanted to know if there is a way that we can handle scenarios like the following
Assuming I have an API that returns some value as boolean, but i want to make a check in my schema that it has to be always true and if it is sent as false. My case must fail. Something line we define enums for strings

**Comment by harikrishnan83** [comment]
hello @GagandeepSharma060 , all your questions and points are absolutely welcome. Thanks a lot for all the issues you have raised :).

On this question, not sure I follow the use case. Can you please elaborate on the API Design here for my context please?

I am guessing you are looking to restrict the Boolean to a single value at schema level. In OpenAPI 3.0.x, to the best of my understanding, this is not possible. However in OpenAPI 3.1.x, which support more of JSONSchema capabilities we can try using `const` for this. Here is the [documentation](https://json-schema.org/understanding-json-schema/reference/const).

And then the Boolean definition will look something like this.

```yaml
openapi: 3.1.0
components:
  schemas:
    ExampleObject:
      type: object
      properties:
        isActive:
          type: boolean
          const: true
      required:
        - isActive
```

In OpenAPI 3.0.x, we can use enums to restrict a field to a single value.

```yaml
openapi: 3.0.0
components:
  schemas:
    ExampleObject:
      type: object
      properties:
        isActive:
          type: boolean
          enum: [true]
      required:
        - isActive
```

Is this on the lines of what you are looking for?

**Comment by samyakOO7** [comment]
Hello @GagandeepSharma060, Can you please provide inputs as requested by @harikrishnan83  so that we can bring this issue to a closure?

Thanks

**Comment by samyakOO7** [comment]
Hey @GagandeepSharma060, Just a pleasant reminder on it.

**Comment by GagandeepSharma060** [comment]
Yes @samyakOO7. Seems fine, no further questions. Thanks for the reply and apologies for late response.

**Comment by samyakOO7** [comment]
Thank you for your kind response. We truly appreciate your support and are happy to assist further if needed. Please don't hesitate to reach out with any additional questions or feedback. Closing the issue as of now!
