### ISSUE TITLE
Retrieve Specmatic Text Error Messages for setExpectationJson

### ISSUE THREAD

**Issue by Rajaneeshkumar** [specmatic/specmatic#1429]
**Is your feature request related to a problem? Please describe.**
Since Specmatic returns error messages in text format, retrieving detailed error information from _specmatic/expectations in the setExpectationJson method has been challenging. Previously, only the error code was captured, making it difficult to identify which fields were incorrect or missing according to the OpenAPI specifications. This update addresses the issue by capturing and logging the full text error message, enabling more precise troubleshooting.

**Describe the solution you'd like**
Added error handling to return error message also along with error code.

**Additional context**
![image](https://github.com/user-attachments/assets/f6d2181a-122a-4363-8dd6-36e7a44e9659)

**Comment by Rajaneeshkumar** [comment]
@harikrishnan83 [pranavgawri](https://github.com/pranavgawri)
I made code changes as part of this PR, this is more of NODE related request.
https://github.com/znsio/specmatic-node/pull/162

Can you guys please review this and suggest if more changes required

**Comment by harikrishnan83** [comment]
Thanks @Rajaneeshkumar. We are reviewing your PR and will get back shortly.

**Comment by samyakOO7** [comment]
Thanks @Rajaneeshkumar for helping out here, it's nice to have your contribution to our project. Feel free to add up with any further suggestions or questions, you are most welcome. Hence forth, I am marking this issue as resolved
