### ISSUE TITLE
Specmatic not giving enough info while doing generative 400 bad request scenario

### ISSUE THREAD

**Issue by twinkle12b** [specmatic/specmatic#1439]
Hello @harikrishnan83 I am facing difficulty in analysing why is specmatic expecting 400 bad request where my system is doing a 201 success. As for usual test scenarios I can see that specmatic in logs provides info on bad data it is sending in headers, but for a specific case just says
-ve scenario: POST /pets -> 4xx Failed
Can you help me if how can I find the invalid input specmatic is sending which it expects to fail

**Comment by harikrishnan83** [comment]
Hello @twinkle12b, thanks for reaching out.

I would recommend looking into the interactive HTML report (you will find it in `build/reports/specmatic/html/index.html`) to understand the request being sent and the particular mutation being done for `-ve` tests.

At its heart, Specmatic API resiliency tests are inspired by mutation testing and property based testing. Here is a [video](https://youtu.be/iIOYeJc597c?t=934) that goes into the details.

If you have further questions please feel free to reach out to us on [https://specmatic.io/contact-us/](https://specmatic.io/contact-us/) and we can setup a quick call to help answer your questions. Hope this helps.

**Comment by yogeshnikam671** [comment]
Hi @twinkle12b, closing this issue out for now as it's already been answered by Hari.
Please feel free to reopen the same if you have any further questions.
