### ISSUE TITLE
Support use of anyOf

### ISSUE THREAD

**Issue by depopry** [specmatic/specmatic#1464]
My specifications use the anyOf discriminator, which I see is not current supported in the codebase. This would be extremely beneficial for my use-case, as it's used somewhat prolifically.

**Describe the solution you'd like**
Support use of anyOf. [Resolve raising this exception](https://github.com/znsio/specmatic/blob/a14f07df2da08d90d6f716aa0b18b77eb205ced1/core/src/main/kotlin/io/specmatic/conversions/OpenApiSpecification.kt#L1408).

**Describe alternatives you've considered**
We could set a standard to not use anyOf, but this is not preferable.

**Comment by harikrishnan83** [comment]
hello @depopry , thanks for reaching out. We do not support `anyOf` because it makes for a completely loosely defined schema. May I know what is your use case for `anyOf`?

**Comment by samyakOO7** [comment]
Hey @depopry, a gentle reminder on this, kindly can you let us know the use case of ```anyOf``` as per your specification?

**Comment by harikrishnan83** [comment]
hello @depopry , I am closing this issue for now. Please feel free to re-open if you have any questions on this or any specific use case that requires use of `anyOf`. Thanks.

**Comment by GagandeepSharma060** [comment]
Hi @harikrishnan83 , was just going through the open issues and stumbled upon this. I agree with you that the use of anyOf will lead to a loosely defined schema but I believe there will be some use case for this. The usage will depend on if we want our schema to be very strct or not but having the support for anyOf will be a great idea. TBH I also tried doing the same for one of my use case but was not able to do it as specmatic do not support
