### ISSUE TITLE
Specmatic Python Causing issues due syntax issue.

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#1502]
**Description**
This line is causing issue as template string has double quotes inside double quotes 
`test_name = f"test [{unique_id}] {testcase.get("name")}"  `
Please update this to 
`test_name = f"test [{unique_id}] {testcase.get('name')}"`

https://github.com/znsio/specmatic-python-extensions/blob/91a5391f7d636990f8fc281539e79217eca3fef3/specmatic/generators/test_generator_base.py#L18

**Comment by harikrishnan83** [comment]
@barath121 Thanks for reporting this. We will take a look.

**Comment by barath121** [comment]
@harikrishnan83 Is this fixed?

**Comment by harikrishnan83** [comment]
@barath121 the fix is on its way, will be part of 2.0.50 release which will be done today. Will update you as soon as it is done. Thanks.

**Comment by harikrishnan83** [comment]
hello @barath121 , this has been address in our latest [release 2.0.50](https://pypi.org/project/specmatic/). Kindly check and let us know. Closing this for now. Please feel free to reopen if you have any questions on this. Thanks.
