### ISSUE TITLE
Array fields are missing in the Examples of the generated spec through sample request and response

### ISSUE THREAD

**Issue by sahilaug** [specmatic/specmatic#205]
**Description**
Array fields are missing in the Examples of the generated spec through sample request and response

**Steps to reproduce**
1. Use the sample request response file: scheduleMeetingSample.json in [scheduleMeetingSample.json.zip](https://github.com/znsio/specmatic/files/6269343/scheduleMeetingSample.json.zip)

2. Run this command: `specmatic import stub -o scheduleMeeting.spec scheduleMeetingSample.json`
3. The command generates a new spec file called scheduleMeeting.spec

**Expected behavior**
Array fields like daysOfWeek, weeksInMonth and participants should be part of examples in the newly generated spec file

**Additional context**
Specmatic version: 0.24.2
OS: MacOS

**Comment by jaydeepk** [comment]
Hi @sahilaug 
Apologies for the delayed response.
We'll have a look at this and get back to you.

**Comment by jaydeepk** [comment]
Hi @sahilaug 
We have transitioned out of gherkin now.
Could you please check if the issue persists with open api specifications too.
Closing this for now, please feel free to reopen.
