### ISSUE TITLE
Ability to dynamically send time parameters in the request ,for creating meeting, startTIme endtime etc which are the details in the examples

### ISSUE THREAD

**Issue by SarveshSharma101** [specmatic/specmatic#223]
**Is your feature request related to a problem? Please describe.**
The API, that I am working on requires me to get the meetingId of a meeting that has started and not expired at the same time.
It should be an ongoing meeting. Hence having predefined meeting details already in the database doesn't work as it gets expired after some time

**Describe the solution you'd like**
 Being able to dynamically create a meeting by calling the respective spec file and sending parameters as request body, to the meeting contract test. As a result, create the meeting with the desired start and end time.

**Additional context**
- If the meeting is not started the API throws an error as "Meeting not started yet"
- ![1](https://user-images.githubusercontent.com/31402933/115839523-5ec49f00-a438-11eb-8402-443c7a2fc326.PNG)

- If the meeting has ended the API throws an error as "Meeting has been expired"
- ![2](https://user-images.githubusercontent.com/31402933/115839530-5ff5cc00-a438-11eb-86b4-8e4fefeed9f3.PNG)

**Comment by sahilaug** [comment]
Moving this feature request to specmatic-node project as it fits the helper library
