### ISSUE TITLE
Not able to import 2 different response values individually  which are exported from 2 different spec file

### ISSUE THREAD

**Issue by SarveshSharma101** [specmatic/specmatic#224]
**Description**
When 2 different values are imported from 2 different spec files, both the values are combined together and displayed as single object. This eventually leads to not running any of the contract tests.

**Steps to reproduce**
1. Export 2 different response values from 2 different spec files
2. define the path for the files in the specmatic.json file inside "baseurls:"
3. import both the response values inside a single spec file and try to use it via examples eg:($auth.Otttoken)

**Expected behavior**
Being able to access each imported values individually

**Screenshots**
1. exporting values from 2 different files
![a](https://user-images.githubusercontent.com/31402933/115844172-34291500-a43d-11eb-8dfc-f9136e8db76f.PNG)
![b](https://user-images.githubusercontent.com/31402933/115844177-34c1ab80-a43d-11eb-9d25-80bf15c88b9a.PNG)

2. defining path in specmatic.json
![t](https://user-images.githubusercontent.com/31402933/115845067-1d36f280-a43e-11eb-907c-6afb1f06393f.PNG)

3. Importing values in spec files we want those values in
![d](https://user-images.githubusercontent.com/31402933/115844407-69cdfe00-a43d-11eb-90a2-0580d800c347.PNG)
![t4](https://user-images.githubusercontent.com/31402933/115853242-96d2de80-a446-11eb-9919-c1996c71f12a.PNG)

4. Error
![t3](https://user-images.githubusercontent.com/31402933/115853216-8fabd080-a446-11eb-84dc-091bc92e99c8.PNG)

**System Information:**
 - Windows 10
 - Specmatic version: [e.g. 0.25.1]
 - OpenJDK version: [e.g. 13]

**Comment by joelrosario** [comment]
Fixed by commit id 1742bd15a41a5e8a3edfba19e8fd2f8703804819
