### ISSUE TITLE
Recommended way to share data-types between files?

### ISSUE THREAD

**Issue by saurabhnanda** [specmatic/specmatic#233]
I started out with specmatic today and hit my very first problem in the first 5 minutes. In a complicated API project, how do I define data-types in one place to be reused by multiple `feature` files?

**Comment by vikram-rao** [comment]
Hey @saurabhnanda , you can `$ref` syntax in a open API spec file like -

```
...
      $ref: '#/components/schemas/Product'
...
components:
  schemas:
    Product:
      title: Product Details
      type: object
      properties:
        name:
          type: string
        id:
          type: integer

```

In fact this referred component can be in an another file too in which case you can refer to it by 
```
    $ref: './common.yaml#/components/schemas/Product'
```
Here, `common.yaml` is a file containing commonly used data types that can referred too in other contract files.

**Comment by harikrishnan83** [comment]
@saurabhnanda Hope @vikram-rao 's response answers your question. Closing this issue.
