### ISSUE TITLE
How do I specify minlength/maxlength of a data-type?

### ISSUE THREAD

**Issue by saurabhnanda** [specmatic/specmatic#235]
Say I want to define a common data-type for the Indian postal codes (PIN code), which should be exactly 6 characters in length. How do I do this in specmatic, such that:

- req/res with this field are automatically validated to have PIN codes of exactly six characters in length?
- the stub server generated random pin codes with exactly six characters? (actually a string of six characters consisting only of numbers)

**Comment by harikrishnan83** [comment]
Thank you for posting this question. This should be supported in the next release for Strings. Please see "Length Restrictions" in [docs](https://specmatic.in/documentation/language.html#built-in-data-types).
