### ISSUE TITLE
Specmatic should be able to pick values in response from incoming request /url or headers

### ISSUE THREAD

**Issue by samdqa** [specmatic/specmatic#253]
**Is your feature request related to a problem? Please describe.**
We have specific use cases where we require some response values to be same as that passed as part or request url/body/headers . This restricts us from creating static stubs resulting in overhead for calling expectations. Sometimes as a client we are even unaware of some values added by interim components and the downstream system needs the exact same value else it will fail [False failures ] 

**Describe the solution you'd like**
We want to have a implementation in specmatic very similar to how it reads examples for request
ex : 
Feature: Summary API of test cart

  Scenario: Create cart API
    Given json SummaryRequest
      | Request | (Request) |
    And json Request
      | Body   | (Body)   |
      | Header | (Header) |
    And json Header
      | Header1    | (string) |
      | Header2 | (number) |
      | RequestId   | (string) |

    And json Body
      | userId    | (number) |
      | mobile | (number) |

    And json SummaryResponse
      | Control | (Control) |
      | Data    | (Data)    |
    And json Control
      | Status      | (number) |
      | Message     | (string) |
      | TimeTaken   | (string) |
      | MessageCode | (number) |
      | CartId | #(URL:CartId) |

    When POST /app/cart/(CartId:number)/createCart
    And request-header APPVersion (string)
    And request-header Product (string)
    And request-header Version (number)
    And request-body (SummaryRequest)

    Then status 200
    And response-body (SummaryResponse)

In this example we want the response to have cartId in control section of response to be same that was sent int URL section . This will also help if there are any async calls which will send the response later to the clients with references for processing

**Describe alternatives you've considered**
Currently we create expectations for each test case to set this values but in few cases where this value is not in our control we look for the latest id in DB and send a +1 to that in expectation[This approach will not work in parallel setup]

**Additional context**

**Comment by jaydeepk** [comment]
Thanks for reaching out to us @samdqa .
Apologies for the delayed response.
I would like to confirm if this is still an issue for you?
I'm not sure if there is an open api compliant way to achieve what you need.

**Comment by harikrishnan83** [comment]
@samdqa Thanks for your patience. This is indeed supported in Specmatic. Here is the [documentation](https://specmatic.in/documentation/service_virtualization_tutorial.html#externalised-response-generation).

However I notice that your issue description contains our Gherkin DSL syntax. We have moved to OpenAPI as our preferred way of specifying Http REST applications.

Closing the issue. Please re-open or file other issues if you need any other help.
