### ISSUE TITLE
HTML report to contain contract-tests details

### ISSUE THREAD

**Issue by nidhi-tomar93** [specmatic/specmatic#257]
**Is your feature request related to a problem? Please describe.**
Currently, there is just an .XML file getting generated as part of test report.

**Describe the solution you'd like**
I would like to include the contract tests details in the HTML report that is getting generated via "surefire" for better reporting structure.

**Comment by vikram-rao** [comment]
Hi @nidhi-tomar93 , it has been a while but we are finally looking into this. Thanks for your patience.

**Comment by harikrishnan83** [comment]
hello @nidhi-tomar93, apologies for the radio silence. Specmatic contract test run as part of regular Maven and Gradle lifecycle methods the rendering to HTML is already taken care of by Surefire plugin. Can you please check again and let us know if we are missing anything? Closing for now. Please feel free to reopen. Thanks.
