### ISSUE TITLE
Need provision to modifiy HTML report contents for contracts and API tests 

### ISSUE THREAD

**Issue by nidhi-tomar93** [specmatic/specmatic#258]
**Is your feature request related to a problem? Please describe.**
Currently, there is no way to add relevant content to the HTML report. It gets generated on its own.

**Describe the solution you'd like**
I would like to have a file from where I can modify the contents that I need in the HTML report.

This feature request depends on #257.

**Comment by sahilaug** [comment]
1) Currently, there are no HTML reports generated 
https://github.com/znsio/specmatic/issues/257 will add that.
2) When the above feature is added, even then it will not be editable. Reports are always autogenerated. @nidhinavya can you please clarify why do you need to edit the reports
3) specmatic will generate HTML reports for contract tests, not for any API tests that you might be using other tools to write
