### ISSUE TITLE
HTML report shows all the files after using "-Dtag="

### ISSUE THREAD

**Issue by nidhi-tomar93** [specmatic/specmatic#259]
**Is your feature request related to a problem? Please describe.**
HTML report shows all the available files after using the "-Dtag=" and sometimes it shows the error for all the files. 

**Describe the solution you'd like**
HTML report should contain only the selected file from "-Dtag=@fileName" and should exclude others from the HTML report.

**Comment by sahilaug** [comment]
-Dtag that is being referred here is part of karate API not specmatic
