### ISSUE TITLE
Multiple API Endpoints are not getting called in a single scenario

### ISSUE THREAD

**Issue by ZenasMukadom** [specmatic/specmatic#270]
**Is your feature request related to a problem? Please describe.**
1. Unable to hit multiple API Endpoints in a single scenario
2. Unable to get the response data from the previous API call and not able to use it in the next API request(part of same scenario).

**Describe the solution you'd like**
1. Specmatic should support multiple API endpoint calls in a single scenario.
2. User should be able to store the response data from the previous API call and should be able to reuse it in the same scenario.

**Comment by sahilaug** [comment]
This can be done by using a first API call in a separate spec file that exports the required field and using that value in the second spec file.
