### ISSUE TITLE
Need a global-config to move hard-coded data from .spec

### ISSUE THREAD

**Issue by nidhi-tomar93** [specmatic/specmatic#272]
**Is your feature request related to a problem? Please describe.**
Hardcoding testData in .spec file is not a good practice. It's fine in the case of 10-20 APIs but, it will be hard to maintain in case of a large number of APIs(>100).

**Describe the solution you'd like**
There should be a config file to store the reuseable data and use the variable reference from config in the other files.

**Comment by joelrosario** [comment]
@nidhi-tomar93 have a look at the following:
- https://specmatic.in/documentation/specmatic_json.html#declare-environment-configuration
- https://specmatic.in/documentation/authentication.html#setup-the-auth-credentials

I'm closing this ticket. But feel free to reopen it if this is not what you're looking for.

**Comment by nidhi-tomar93** [comment]
@joelrosario, I am able to store the value in the single level JSON variable.

But, getting below the error while using the multilevel JSON for storing the value.
Error: Could not find reference to value "loginData.ott.email"
