### ISSUE TITLE
NullPointer Exception when we run the contract test in which the whole feature/code in it is commented 

### ISSUE THREAD

**Issue by ZenasMukadom** [specmatic/specmatic#295]
**Description**
When we comment the whole feature in a contract test and run that file, Specmatic gives "NullPointer Exception" in the terminal, and specmatic stops running the remaining contract test even if there are still more contracts present in specmatic.json which need to be executed. 

**Steps to reproduce**
1. Create a Spec file and comment the whole feature in it and add the path in specmatic.json file
2. Run this script: specmatic test --host=localhost --port=5000 --env=local 

**Expected behavior**
Specmatic should not produce NullPointer Exception and run the remaining files without getting terminated and should display the test run count >0.

**Screenshots**
![Specmatic Bug](https://user-images.githubusercontent.com/53227610/125282799-66a82700-e335-11eb-9a65-ae698d4b4e36.PNG)

**System Information:**
 - OS & version: Windows 10 Enterprise 64-bit
 - Browser & version: Chrome ver - 84.0.4147.135
 - Specmatic version: 0.28.5
 - JDK version: openjdk 13

**Comment by jaydeepk** [comment]
Thanks for reaching out @ZenasMukadom .
Apologies for the delayed response.
We'll have a look at this.

**Comment by jaydeepk** [comment]
@ZenasMukadom 
We have transitioned out of having api contracts described in gherkin format to leveraging api specifications such as OpenAPI, WSDL, AsyncAPI, etc.
Do take a look at your [website](https://specmatic.in/).
Closing this issue for now, please feel free to reopen.
