### ISSUE TITLE
Need sleep/wait function in Contract test

### ISSUE THREAD

**Issue by ZenasMukadom** [specmatic/specmatic#329]
**Is your feature request related to a problem? Please describe.**
I have an API that gives two types of responses. When we hit the API the first time the response sent by the API is => success and when we hit the API again the second time without waiting for few seconds it gives the response => "Please wait for some time".

**Scenario** 
1. Endpoint : api/vehicles -   Request : body :{ type:"car" } , Response : success 
2. Endpoint : api/vehicles -  Request : body: { type:"bike"}, Response : success 

So If I call the API with Scenario 1, it will give me a response: success, and then when I call the 2 Scenario with a different request value it will give me a response: "Please wait for some time". This happens because there is no wait time between these Scenarios and hence the actual response is different from the expected response.

**Describe the solution you'd like**
I would like to have a sleep/delay function to be called between these two scenarios so that after calling the 1st Scenario it waits for a couple of seconds/minutes and then calls the 2nd Scenario which then will give response as -> success, and not response as -> "Please wait for some time"
Actual Response: "Please wait for some time"
Expected Response: success

**Describe alternatives you've considered**
Need to create a sleep/wait Function in specmatic for contract tests. And use the sleep/wait function in the contract test
example: And def sleep(2000)
I would like to implement it myself if possible.

**Additional context**
The way I would want to define and use it in the contract test:

Scenario: User gets the  message
   Given type RequestBody
     | type | (string) |
   And type ResponseBody
     | message    | (string) |
   And def sleep(2000)
   When POST /api/vehicles 
   And request-body (RequestBody)
   Then status 200
   And response-body (ResponseBody)
   Examples:
   | type  |
   | car    |

**Comment by jaydeepk** [comment]
@ZenasMukadom Thanks for reaching out to us.
Apologies for the delayed response.
Just want to check is this is still an issue for you, or did your workaround suffice.
Adding the sleep keyword in the spec may not be ideal as then the spec won't be open api compliant.

**Comment by harikrishnan83** [comment]
@ZenasMukadom in general our tests are designed to run as a fast as possible and also in parallel to give quick feedback. Adding delays is usually considered anti-pattern because "slow test" = "no test". This looks like more like restrictions (throttling, etc.) that we may expect in production like environments. Specmatic contract as tests should ideally be run locally, in CI or in any other component test like environment. Closing this issue for the moment. Please feel free to re-open if you are still looking for a solution here.
