### ISSUE TITLE
Stub in lenient (not strict) mode is not checking presence of query parameters in URL

### ISSUE THREAD

**Issue by harikrishnan83** [specmatic/specmatic#45]
Contract

```
Scenario Outline: Fetch pet details
       When GET /pets/(id:number)?name=(string)
       Then status 200
       And response-body (name:string)`
```

Stub

```
{
      "http-request": {
          "method": "GET",
          "path": "/pets/2",
          "query": {
              "name": "Archie"
          }
      },
      "http-response": {
          "status": 200,
          "body": "Golden Retriever"
      }
}
```

Curl

`$ curl -vs http://0.0.0.0:9000/pets/2 2>&1 | less                                                                         
Golden Retriever`

It is matching without query parameter. This should not happen. It should ideally verify if at least the query parameter name is present.

**Comment by joelrosario** [comment]
This happens even with the strict mock. If a query param is provided, the name and value are both validated. If no params are provided, the stubbed response is returned as in the above example.

**Comment by harikrishnan83** [comment]
@joelrosario Tested this today, stub command hangs with the above inputs. Can you please check?

**Comment by joelrosario** [comment]
@harikrishnan83 Thanks. This doesn't hang for me with the above inputs. Are you certain you're trying with the latest?

**Comment by harikrishnan83** [comment]
@joelrosario The command I am running is `java -jar ~/Downloads/qontract.jar stub ~/test.contract`. This issue is reproducible with release https://github.com/qontract/qontract/releases/tag/0.17.0. Please let me know if I have got the command wrong. The contract and stub is as per what I have already shared.

**Comment by harikrishnan83** [comment]
@joelrosario I found the issue. It had to do with a typo in the name of the contract file extension. I will raise another bug for error reporting and then close this issue itself. The stubbing is working as expected. Thanks.
