### ISSUE TITLE
So we tried upgrading cucumber to latest version 19.1.2 (by upgrading specmatic-core from 0.31.0 to 0.47.0), but after this upgrade our contract tests started failing with following error:  Failed xxxxx.TestxxxxxContracts.contractAsTest  Stacktrace java.lang.NoClassDefFoundError: io/cucumber/messages/IdGenerator$Incrementing Caused by: java.lang.ClassNotFoundException: io.cucumber.messages.IdGenerator$Incrementing  Standard Output Starting the Contract Tests Neither contract nor config were specified, defaulting to ./specmatic.json Loading config file ./specmatic.json Using contracts from .specmatic_test_bundleXXXXXXX io/cucumber/messages/IdGenerator$Incrementing; io.cucumber.messages.IdGenerator$Incrementing  We are using -  <cucumberxxxx.version>19.1.2</cucumberxxxxx.version> <specmatic.version>0.47.0</specmatic.version>

### ISSUE THREAD

**Issue by workprakash19** [specmatic/specmatic#498]
**Description**

**Steps to reproduce**
1. Create a file ...
2. Run this command: ...
3. Make an http request looking like this: ...

**Expected behavior**

**Screenshots**

**System Information:**
 - OS & version: [e.g. MacOS 10.15.7]
 - Browser & version: [e.g. chrome, safari]
 - Specmatic version: [e.g. 0.17.0]
 - JDK version: [e.g. 14]

**Additional context**

**Comment by harikrishnan83** [comment]
@workprakash19 Thanks for reporting the issue. I just verified the latest version of Specmatic on our [sample project](https://github.com/znsio/specmatic-order-api) and it is working. The class not found in the issue description is related to a [cucumber messages jar](https://mvnrepository.com/artifact/io.cucumber/messages/17.1.1). Can you please check if you have this in your External Dependencies?

Also Specmatic does not need you to upgrade the cucumber version by yourself. If you just upgrade Specmatic to 0.47.x it should automatically pull a suitable cucumber version.

**Comment by mithiladharankar** [comment]
Removed the cucumber dependency, the above issue is resolved. Now contract tests are failing.
This ticket can be closed, created new ticket for the contract tests

**Comment by workprakash19** [comment]
Thanks for the support.

**Comment by harikrishnan83** [comment]
Thanks @mithiladharankar and @workprakash19
