### ISSUE TITLE
More number of contract test executed on upgrade of specmatic-core

### ISSUE THREAD

**Issue by mithiladharankar** [specmatic/specmatic#499]
After upgrade of specmatic-core from 0.31.0 to 0.47 more number of contract tests are getting executed and failed. 
In our scenario for :
version 0.31.0 -> 65 testcases executed 
0.38.0 , 0.46.0, 0.47.0 -> More than 200 testcases executed and are failing.

**Comment by harikrishnan83** [comment]
@mithiladharankar thanks for reporting the issue, we will take a look

**Comment by joelrosario** [comment]
@mithiladharankar there is a fix out for this with 0.50.0. Please try it out and let me know if it works.

**Comment by mithiladharankar** [comment]
@joelrosario We tried out with  0.50.0. version of specmatic. Still could see more number of testcases being executed at our end.
Observation : Testcases run with permutation combination for optional fields.
For e.g if field is boolean, testcases executed with both values true and false

**Comment by joelrosario** [comment]
Hi @mithiladharankar, I was unable to replicate the problem. I have tried this with an enum and a bool in the contract, wrapping them in a .spec file and providing examples.

Here is [the test that I wrote](https://github.com/znsio/specmatic/blob/5fcbdbd3ef374359d992bab6c84fce10464b4692/core/src/test/kotlin/in/specmatic/core/FeatureTest.kt#L933), which passes on my laptop. Here is the [OpenAPI contract](https://github.com/znsio/specmatic/blob/too_many_tests_non_string/core/src/test/resources/openapi/one_enum_one_bool.yaml) that it uses (the wrapper spec file is built into the test).

I tested the same scenario with an actual spec file wrapping a yaml file, and was not able to replicate it.

Is it possible that in your testing, you are invoking the yaml file directly? It would not have examples, and hence would generate the additional tests we are seeing.

If not, then I'd need your help to replicate the issue.
1. Can you provide the exact steps that trigger this.
2. Can you provide a stripped down version of the relevant contract and spec file.

Thanks.

**Comment by mithiladharankar** [comment]
Hi @joelrosario 
As per our observation, the tests executed are not as per the examples provided in the .spec file.
Other test scenarios including the optional parameters values are executed.
We expect only the test scenarios mentioned in the examples of the spec file.
Please find the required details as below for your references:
Spec file :

Feature: ################################

  Background:
    Given openapi ###########.yaml

  Scenario: Should respond 200 for #############
    When GET /path/param1
    Then status 200
    Examples:
      | Request-ID | Content-Type | Token |
      | abc  | application/json | TestToken |

  Scenario: Should respond 200 for ###################
      When GET /path/param1?param4=true
      Then status 200
      Examples:
        | Request-ID | Content-Type | Token | param4 |
        | abc  | application/json | TestToken | true |

Contract : 

openapi: 3.0.1
info:
  title: API
  description: #######################
  version: 1.0.0
  contact: {}
servers:
  - url: ##########################
    description: Generated server url
tags:
  - name: #####
paths:
 path/{param1}:
    get:
      tags:
        - ###################
      summary: #################################
      description: ###################################
      operationId: ##############################
      parameters:
        - name: param1
          in: path
          required: true
          schema:
            type: string
        - name: param2
          in: query
          required: false
          schema:
            type: string
        - name: param3
          in: query
          required: false
          schema:
            type: string
        - name: param4
          in: query
          required: false
          schema:
            type: boolean
        - name: Token
          in: header
          required: true
          schema:
            type: string
        - name: Request-ID
          in: header
          required: true
          schema:
            type: string
        - name: Content-Type
          in: header
          required: true
          schema:
            type: string

Please let us know if anything else is required.
Here 2 scenarios are mentioned in the spec file and currently with specmatic version 50 , 12 scenarios are getting executed.

Thanks

**Comment by harikrishnan83** [comment]
@mithiladharankar thanks again for the clarification. In effect what we need here is the ability to completely not send a particular query parameter. We are adding the ability to explicitly "OMIT" a query parameter in the example row. Here is an example:

hello.yaml

```yaml
openapi: 3.0.0
info:
  title: Sample API
  description: Sample API
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
 paths:
  /hello:
    get:
      summary: hello world
      description: Says hello
      parameters:
        - in: query
          name: message
          schema:
            type: string
          required: true
          description: Greeting Message
        - in: query
          name: name
          schema:
            type: string
          required: true
          description: Name of person to greet
        - in: query
          name: another_message
          schema:
            type: string
          required: true
          description: additional message
      responses:
        '200':
          description: Says hello
          content:
            application/json:
              schema:
                type: string
```

hello.spec

```gherkin
Feature: Hello world

Background:
  Given openapi <path to openapi file>/<hello.yaml>            

Scenario: hello with examples
  When GET /hello
  Then status 200
  Examples:
      | message | name   |
      | hello   | Hari   |
      | hello   | (omit) |
```

This should generate 4 tests with below query parameter combinations
* Example Row 1
  * message and name - ```GET /hello?message=hello&name=Hari```
  * message, name and additional message (generated value since it is not provided in example row) - ```GET /hello?another_message=(string)&message=hello&name=Hari```
* Example Row 2
  * message and additional message (generated value since it is not provided in example row), name is skipped - ```GET /hello?another_message=(string)&message=hello```
  * message only - ```GET /hello?message=hello```

This will be part of our next release 0.58.0. Please do let us know if you have any questions.
