### ISSUE TITLE
Failed maven build, passing IDE tests, no clear error accessible

### ISSUE THREAD

**Issue by gstanek** [specmatic/specmatic#508]
**Description**
I'm attempting to incorporate specmatic contract tests into my Java project, using maven to bring in Specmatic and run a junit5 test. In the IDE, the generated contract tests all pass. When I run a `mvn clean install`, the tests quickly fail.

**Steps to reproduce**
1. run `mvn clean install` on my project

**Expected behavior**
All tests pass, as well as the build. Or, if it fails, I'm able to see a helpful error message indicating what I need to investigate. Are there any ways to get to more details of the underlying error?

**Screenshots**
```
[ERROR] contractTest[1]  Time elapsed: 0.061 s  <<< FAILURE!
java.lang.AssertionError: 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'
```

**System Information:**
 - OS & version: MacOS 12.5.1
 - Browser & version: NA
 - Specmatic version: 0.50.0
 - JDK version: adoptopenjdk-11.jdk

**Additional context**
It's possible this is a dependency conflict issue with kotlin. I've tried various dependency overrides, and none have seemed to help. In addition to the specmatic dependency, I am explicitly referencing the `kotlin-stdlib-jdk8` dependency using version `1.7.10` as well to override other versions brought in that cause other ClassNotFound exceptions.

```
        <dependency>
            <groupId>in.specmatic</groupId>
            <artifactId>junit5-support</artifactId>
            <version>0.50.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
            <version>1.7.10</version>
            <scope>test</scope>
        </dependency>
```

**Comment by joelrosario** [comment]
Hi @gstanek 

I agree, seems like a dependency issue.

A couple of ideas:
- Spring references Kotlin and this may be the source of the conflict. If your project is based on an old version of Spring and don't need the Kotlin libraries in it, you could try setting the <kotlin.version> property to 1.7.10
- If not or if that doesn't work, and if you are using IntelliJ Idea, you could try generating an "Effective POM". Right click on the pom.xml in the Project view that shows the list of files, select Maven, select Show Effective POM. This should show you all the dependencies being pulled in, and you can see if any of the Kotlin dependencies here need to be overridden.

**Comment by gstanek** [comment]
I did resolve this by ensuring I had no versions of `org.jetbrains.kotlin:kotlin-stdlib` brought in via other dependencies that was below `1.4.0`.
