### ISSUE TITLE
AsyncAPI support

### ISSUE THREAD

**Issue by pablo-curiel** [specmatic/specmatic#571]
Hi everyone.

I'm trying to use Specmatic for AsyncAPI Contract testing, but I'm not sure it is supported yet.

In [Specmatic home page](https://specmatic.in/), AsyncAPI is listed as one of the **Supported Specification Standards**. But when trying to run the test command against an AsyncAPI file I get the following error message.
```
$ java -jar specmatic-0.59.0.jar test asyncapi.yaml 

Error parsing file asyncapi.yaml
  attribute openapi is missing
Could not parse contract asyncapi.yaml, please validate the syntax using https://editor.swagger.io
Load Error FAILED
Reason: Could not parse contract asyncapi.yaml, please validate the syntax using https://editor.swagger.io
```

Am I doing something wrong, or AsyncAPI isn't really supported yet? If not, is this on the roadmap? Will it be supported in the near future?

**Comment by harikrishnan83** [comment]
@pablo-curiel Thanks for reaching out. We are currently in private beta for async-api support. If you are interested in signing up to participate in our private beta, can you please share your contact information [here](https://specmatic.in/contact-us/) so that we can reach to you on this?

**Comment by harikrishnan83** [comment]
@pablo-curiel We have received your interest to participate in async-api private beta. Will continue the conversation in a separate thread. Closing this issue. Thanks.
