### ISSUE TITLE
Failed Gradle Build with Error "void kotlin.jvm.internal.FunctionReferenceImpl."

### ISSUE THREAD

**Issue by jasonftse** [specmatic/specmatic#572]
**Description**
I am trying to incorporate specmatic contract tests (provider side) into my Java project. When I run the contract tests in IDE (VSCode) it generated contract tests and executed them without issue. But when I run the Gradle(version 6.8.2) Build it failed.

**Steps to reproduce**
Open Java Project with VSCode, then run the Gradle Build.

**Expected behavior**
Contract Tests failed with 'void kotlin.jvm.internal.FunctionReferenceImpl.<init>(int, java.lang.Class, java.lang.String, java.lang.String, int)'.

**Attached error report text file:**
[error_report.txt](https://github.com/znsio/specmatic/files/10345928/error_report.txt)

**System Information:**

- OS & Version: MacOS Ventura 13.0.1
- MacBook Pro: Apple M1 Pro
- Specmatic Version: 0.58.0
- Spring Boot Version: 2.5.8
- Java Version: 11
- Gradle Version: 6.8.2 

**Attached Gradle Build File:**
[build_gradle.txt](https://github.com/znsio/specmatic/files/10345988/build_gradle.txt)

In my grade.properties file I defined "kotlin.version=1.7.20"

**Comment by jaydeepk** [comment]
Thanks for reaching out to us @jasonftse .
Apologies for the delayed response.
Just want to check if you are still facing this issue?

**Comment by jaydeepk** [comment]
Hi @jasonftse 
You have rightly set the Kotlin version to 1.7.20.
You may also need to set the Kotlin Coroutines version to 1.6.4.
Closing this issue for now, please reopen this if the issue persists.
