### ISSUE TITLE
Appearance in https://openapi.tools/

### ISSUE THREAD

**Issue by palktonderAtpowelno** [specmatic/specmatic#573]
Why isn't Specmatic a part of the list of OpenAPI tools in https://openapi.tools/? "Selling" Specmatic internally would be easier if it was a little more visible/"official"

**Comment by harikrishnan83** [comment]
@palktonderAtpowelno Thanks for reaching out. We will raise a PR on [https://openapi.tools/](https://openapi.tools/) to make it visible there.

**Comment by harikrishnan83** [comment]
@palktonderAtpowelno I have raised a [Pull Request](https://github.com/apisyouwonthate/openapi.tools/pull/375)

**Comment by harikrishnan83** [comment]
@palktonderAtpowelno Specmatic is now listed in https://openapi.tools/.
