### ISSUE TITLE
Can't add JWT token in local environment

### ISSUE THREAD

**Issue by pupik1989** [specmatic/specmatic#577]
I'm new to specmatic and part of my API is authentication with barear token .

I need to send this token in all my API requests 

I can't find any examples in the docs of how to add the token in local or remote environment 

Please advise if you have any ideas how it can be done   Thanks!

**Comment by harikrishnan83** [comment]
@pupik1989 Thanks for reaching out. If you have defined [bearer auth](https://swagger.io/docs/specification/authentication/bearer-authentication/) in your openapi file, when you run the same as "contract as test" with Specmatic, the auth header will automatically be populated as per your spec. However specifying an exact token is not a recommended approach at "Contract as Test" level. Here is a [detailed explanation](https://specmatic.in/documentation/authentication.html).

Can you please give us some more context on your use case so that we can help you on this?

**Comment by pupik1989** [comment]
I'm working with yaml files and not spec file

I reviewed all the documents and didn't see how to pass the JWT token when running contract tests

Maybe a local JSON file with token can be added to the project if needed, like the authentication for the git repo

In my case, all my endpoints are secure and need to send JWT token in header for make the http call

Hard coded headers with the token also didn't worked

This is the data I'm using in hard coded token
 - name: Authorization
          in: header
          required: true
          schema:
            type: string
          default: "JWT 123"

and this is the error:
Error parsing file tests/services/service.yaml
  attribute paths.'/internal/api/v1/tasks'(get).parameters.[Authorization].default is unexpected

**Comment by harikrishnan83** [comment]
@pupik1989 Thanks for the details.

Here is an example yaml which defines the Authorization header (This is not the recommended approach, even swagger editor suggests that you define security schemes as mentioned in my earlier response, however you can try this to see if it will help you move forward).

```yaml
openapi: 3.0.0
info:
  title: Order API
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/products/{id}':
    parameters:
      - name: id
        schema:
          type: number
        in: path
        required: true
        examples:
          GET_DETAILS:
            value: 10
      - name: Authorization
        schema:
          type: string
        in: header
        required: true
        examples:
          GET_DETAILS:
            value: "JWT 123"
    get:
      summary: Fetch product details
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
              examples:
                GET_DETAILS:
                  value:
                    name: 'XYZ Phone'
      operationId: get-product-id
```

Below is the output of running the above specification as a test where you can see the "Authorization" header being sent.

```shell
% specmatic test test.yaml

--------------------
  Request to http://localhost:9000 at 2023-1-17 11:47:2.115
    GET /products/10
    Authorization: JWT 123
    Accept-Charset: UTF-8
    Accept: */*

...
Some lines omitted for brevity
...

Scenario: Fetch product details. Response: OK GET /products/(id:number) SUCCESSFUL

Tests run: 1, Successes: 1, Failures: 0, Errors: 0
```

Hope this helps. Please let us know if you have any questions on this.

UPDATE: The "default" field is not part of standard OpenAPI syntax for header definition. That is why you are seeing the error. I have moved your sample JWT to the examples section in my above sample OpenAPI code.

**Comment by kodeshPapaya** [comment]
I'm not sure this structure is working in specmatic.
When I run your example, the token is generated automatically and the call fails

`Request to https://****** at 2023-1-17 8:33:3.646
    GET /***/***
    Authorization: DBQTW
    Host: ***
    Accept-Charset: UTF-8
    Accept: */*`

As you can see **Authorization: DBQTW** is a random string and it's changing each time I run the test

I found a workaround to this issue with enum

this is the only way the token is sent with the header:

      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            enum:
              [
                "JWT 123",
              ]

Regarding your recommendation,
Do you have a link to some example of how to implement the security token not hardcoded in YAML file?
in the swagger docs, it only specified how to define the security scheme, but in our case, we running the files as tests
so we need to inject the token into the "test file"

This is an example of a secure endpoint I'm testing and I'm looking for the correct way to send the token outside the openapi file

`get:
     tags:
       - health-controller
     operationId: get_2
     responses:
       "200":
         description: OK
         content:
           '*/*':
             schema:
               type: object
     security:
       - Authorization: []

components:
  schemas:
   securitySchemes:
     Authorization:
       type: http
       scheme: bearer
       bearerFormat: JWT`

**Comment by harikrishnan83** [comment]
@kodeshPapaya I am guessing you have declared a security scheme in OpenAPI and added the Authorization header explicitly as shown in my example above, in which case the security scheme takes precedence and explicit Authorization header as expected. Which is why you may be seeing the random token being sent.

It will help if you have give me a complete sample openapi yaml file so that I can test and recommend how to go about sending the token.

Also if you need more help on this, please feel free to reach us at [specmatic.in](https://specmatic.in/contact-us/) to setup a call with us.

**Comment by jaydeepk** [comment]
@pupik1989,  @kodeshPapaya are you still facing this issue?
Please do let us know if you need any further assistance.

**Comment by GiancarloFusiello** [comment]
Hi all, I'm also new to specmatic (which I'm enjoying btw) and was also trying to find a method to provide a JWT to authenticate requests when testing. I can confirm that @kodeshPapaya solution does work, however, it forces me to add a URL query parameter which is in turn used as a header when testing, which I find puzzling. Also, this results in the rendered version of the openapi-spec.yaml being inaccurate by adding a parameter that is not available on the endpoint/s. 

I was hoping to find a configuration file or cli options for adding headers that are sent in each request when running tests. Is this already an option that I have somehow missed?

**Comment by harikrishnan83** [comment]
@pupik1989 @kodeshPapaya @GiancarloFusiello We have updated our documentation on OpenAPI authentication scheme support where we now allow setting auth tokens, keys, etc. through env variable. Kindly have a look share your valuable feedback. Link to [auth documentation](https://specmatic.in/documentation/authentication.html).
