### ISSUE TITLE
Test cases are being generated for named response examples without any corresponding named request examples

### ISSUE THREAD

**Issue by abhishekbuilds** [specmatic/specmatic#579]
Specmatic is generating test cases for named response examples for standard http error status codes like 429, 501 and 529 which don't have any named request examples<img width="609" alt="Screenshot 2023-01-12 at 11 16 35 AM" src="https://user-images.githubusercontent.com/22167995/211987422-fba325a1-f678-4b55-b84d-390e92476e97.png">

**Comment by jaydeepk** [comment]
Thanks for reaching out to us @abhishekbuilds .
Could you please provide us a sample spec for this so that we can reproduce the issue at our end.

**Comment by harikrishnan83** [comment]
@abhishekbuilds Apologies for the radio silence on this. A lot has changed since last year. Can you please give our [latest release](https://github.com/znsio/specmatic/releases) a go again and reopen this issue if you are still facing the problem.
