### ISSUE TITLE
Using date-time in a query param does not generate a timestamp

### ISSUE THREAD

**Issue by androa** [specmatic/specmatic#580]
**Description**
My API takes two timestamps as query parameters.

**Steps to reproduce**
1. Create a `api.yaml` with 
```yaml
openapi: 3.0.1
info:
  title: New Feature
  version: "1"
paths:
  /customer/name:
    get:
      summary: New scenario
      parameters:
      - name: timestamp
        in: query
        schema:
          type: string
          format: date-time
        example: '2023-01-12T12:53:10.16048'
      responses:
        "200":
          description: New scenario
          content:
            text/plain:
              schema:
                type: string
```
2. Run this command: `specmatic samples api.yaml`

**Expected behavior**
That specmatic creates example requests with timestamps. 

Instead it generates this request (where instead of a timestamp, it is the object ID):
```json
{
    "requestTime": "2023-1-13 0:45:23.750",
    "http-request": {
        "path": "/customer/name",
        "method": "GET",
        "query": {
            "timestamp": "in.specmatic.core.pattern.DateTimePattern@5fef2aac"
        },
        "headers": {
            "Accept-Charset": "UTF-8",
            "Accept": "*/*"
        },
        "body": ""
    }
}
```

**System Information:**
 - Specmatic version: 0.59.0

**Additional context**
It behaves similarly when trying to run it with contract tests. It seems to be some issue with how date-time is serialized.

**Comment by androa** [comment]
The same happens when trying to run it with `SpecmaticJUnitSupport` -  the request becomes:
```
  Request to http://localhost:8080 at 2023-1-13 1:29:54.175
    GET /customer/name?timestamp=in.specmatic.core.pattern.DateTimePattern@372461a9
    Accept-Charset: UTF-8
    Accept: */*
 ```

**Comment by harikrishnan83** [comment]
@androa Thanks for reporting this issue. The details shared by you are really helpful and I was able to reproduce the issues. Also I tested the changes in your [PR](https://github.com/znsio/specmatic/pull/581) and I have [responded with a unit test](https://github.com/znsio/specmatic/pull/581#issuecomment-1384160787) that for the same.
