### ISSUE TITLE
Declaring contracts in configuration with specific branch

### ISSUE THREAD

**Issue by jasonftse** [specmatic/specmatic#582]
In specmatic.json file can we define the branch of the repository?
Thanks.

**Comment by harikrishnan83** [comment]
@jasonftse Thanks for reaching out.

We do not encourage referencing branches in ```specmatic.json``` because that way the provider and consumer may be referring to different versions of the API specification.

Can you please elaborate on why you want to point to a branch?

**Comment by tpwst555** [comment]
> @jasonftse Thanks for reaching out.
> 
> We do not encourage referencing branches in `specmatic.json` because that way the provider and consumer may be referring to different versions of the API specification.
> 
> Can you please elaborate on why you want to point to a branch?

I had the same question.  We would like to promote the specs to dev > stable (default) > main branches so it matches the code that is available in the respective environments.  (dev > uat > prod).  We may be prepping stories for release that are on contract v1 but developing stories with contract v2, etc.  These specs are also presented to clients via swagger ui per environment so they know exactly what is available in each environment.

If specmatic is always pulling from the stable version of the spec, developers are unable to validate their changes against the contract until QA testing is complete and we are in UAT.  

Is it possible to accommodate this type of promotional model with specmatic?

**Comment by harikrishnan83** [comment]
@tpwst555 thanks for sharing details on why you are looking for this capability. We will get back to you on this shortly.

**Comment by harikrishnan83** [comment]
@jasonftse @tpwst555 Branches are now supported in release [0.72.0](https://github.com/znsio/specmatic/releases/tag/0.72.0). Please see [documentation](https://specmatic.in/documentation/specmatic_json.html) for the details.

Thanks to @aeoncl for his [contribution](https://github.com/znsio/specmatic/pull/672).

cc @joelrosario
