### ISSUE TITLE
oneOf only supports first sub-schema

### ISSUE THREAD

**Issue by westse** [specmatic/specmatic#585]
**Description**
Only the first sub-schema of oneOf is supported. Usage of any other sub-schema results in an error.

**Steps to reproduce**
1. See unit test in pull request #586 

**Expected behavior**
Any one of multiple sub-schemas of oneOf should be supported

**System Information:**
 - OS & version: Ubuntu
 - Browser & version: n/a
 - Specmatic version: 0.59.0
 - JDK version: 11

**Additional context**
Also blocks resolution of another bug related to a dictionary with values with oneOf schema #587

**Comment by sergeyklay** [comment]
I think this is related too: https://github.com/znsio/specmatic/pull/588#issuecomment-1399256057

**Comment by harikrishnan83** [comment]
@westse as mentioned by @joelrosario we had to look at this failing scenario 437e242be4650519df78d1445a609b1b0e2bae6a and we have subsequently fixed the same with 24340d8ee6b55b98dc30cfbc378596616460f728
