### ISSUE TITLE
array of enum in query param causes URISyntaxException

### ISSUE THREAD

**Issue by westse** [specmatic/specmatic#589]
**Description**
A URISyntaxException is produced when an OpenApi spec contains a query parameter that is an array of enum, similar to the following.
```
openapi: "3.0.3"
paths:
  /pets:
    get:
      summary: get pets
      description: get pets
      operationId: findPets
      parameters:
        - name: rating
          in: query
          description: ratings to filter by
          required: false
          schema:
            type: array
            items:
              type: string
              enum:
                - 1
                - 2
```

**Steps to reproduce**
1. See unit test in pull request #590 

**Expected behavior**
Should be supported without exception

**System Information:**
 - OS & version: Ubunto
 - Browser & version: n/a
 - Specmatic version: 0.59.0
 - JDK version: 11

**Comment by harikrishnan83** [comment]
@westse this is related to #504
