### ISSUE TITLE
Query param of free-form dictionary produces URISyntaxException

### ISSUE THREAD

**Issue by westse** [specmatic/specmatic#599]
**Description**
Query param of free-form dictionary produces `URISyntaxException: Illegal character in query at index...`

**Steps to reproduce**
1. See pull request  #600 

**Expected behavior**
No exception and free-form dictionary should be supported per OAS 3.x

**Screenshots**
n/a

**System Information:**
 - OS & version: n/a
 - Browser & version: n/a
 - Specmatic version: 0.59.0
 - JDK version: 11

**Additional context**

**Comment by vikram-rao** [comment]
@westse We are reviewing the PR for this issue. Thanks for your patience.
