### ISSUE TITLE
Better Sample Project

### ISSUE THREAD

**Issue by joelrosario** [specmatic/specmatic#60]
**Is your feature request related to a problem? Please describe.**
The usage of qontract is not very evident with the petstore example.

**Describe the solution you'd like**
Need to add a new sample project: ecommerce, which is more relatable to a large majority of people.

**Describe alternatives you've considered**
n/a

**Additional context**
<img width="700" alt="Screenshot 2020-09-21 at 1 04 29 PM" src="https://user-images.githubusercontent.com/126087/93742202-5a6aa600-fc0b-11ea-8cc3-555811d77db2.png">

**Comment by sahilaug** [comment]
@nashjain @harikrishnan83  Need your help here. Please feel free to update the architecture diagram

**Comment by nashjain** [comment]
> @nashjain @harikrishnan83 Need your help here. Please feel free to update the architecture diagram

@harikrishnan83 has updated this diagram. We should take that.

**Comment by harikrishnan83** [comment]
@nashjain taking a look

**Comment by harikrishnan83** [comment]
<img width="700" alt="Screenshot 2020-09-21 at 1 04 29 PM" src="https://user-images.githubusercontent.com/126087/93742053-19729180-fc0b-11ea-8ccb-b23f637e860f.png">

@sahilaug please use this diagram
