### ISSUE TITLE
Provide release notes

### ISSUE THREAD

**Issue by sergeyklay** [specmatic/specmatic#606]
Currently I have to check manually every time what has been changed using the version diff and the list of commits, which is time-consuming. It would be really useful to understand what exactly was fixed/introduced for particular Specmatic version using CHANGELOG.md or GitHub Release notes (which can automatically include a list of changes too). Please start providing release notes for each Specmatic version.

**Comment by joelrosario** [comment]
Hi @sergeyklay, life and our day jobs overtook us for a few days, and we had to push out a release and didn't add release notes. Sorry about that. Release notes are out now, for two versions (0.60.0 and 0.61.0).
