### ISSUE TITLE
Oauth2 Authorization

### ISSUE THREAD

**Issue by stijn-vanhoof-io** [specmatic/specmatic#611]
**Is your feature request related to a problem? Please describe.**
Specmatic only supports bearer and api key authentication (header, query) security schemes at the moment

**Describe the solution you'd like**
Will specmatic support Oath2 security https://swagger.io/docs/specification/authentication/oauth2/ ?

How can I still use specmatic with specs that have oath2 authorization?
Can i ignore the error message and uses bearer tokens myself by fetching a token in beforeAll without changing the actual schema?

Thank you for your help!

**Comment by harikrishnan83** [comment]
@stijn-vanhoof-io Thanks for reaching out to us. OAuth2 support should be available soon. We will keep you posted on this.

**Comment by androa** [comment]
What about the part @stijn-vanhoof-io mentions about simply ignoring this and allowing stubbing the API without the (proper) auth? Not being allowed to define OIDC as an auth mechanism is a pretty big blocker for adoption :/

**Comment by harikrishnan83** [comment]
@androa @stijn-vanhoof-io I am bumping this up our priority list cc @joelrosario @jaydeepk

**Comment by dveljacic** [comment]
Is there some rough timeline for when this should be addressed? Even though we consider using Specmatic and see great potential in it, with all our API specifications having OAuth2 security, it makes it a not viable solution, not even for simple backward compatibility checks with the `compatible` command.

**Comment by kmichnie** [comment]
My team also has this issue and I was also wondering, just like @dveljacic, if there is any time schedule for this?

**Comment by harikrishnan83** [comment]
@kmichnie @dveljacic Thanks for bumping this up. We have now prioritised this and are currently working on it. We will keep you posted on the timelines for this. cc @stijn-vanhoof-io @androa

**Comment by dveljacic** [comment]
@harikrishnan83 @jaydeepk thank you very much guys for prioritizing this issue and tackling it so soon! 🙏 
I'm very glad to see the code for it merged. One question though: It's not part of the latest (0.77.1) release, right? 
When can we expect the release that includes this and/or how can we already create/use the `main` version of the Specmatic (which includes this fix) to test it in our app?

**Comment by harikrishnan83** [comment]
@stijn-vanhoof-io @androa @kmichnie @dveljacic Thank you all for your patience.

OAuth support is available with release [0.78.0](https://github.com/znsio/specmatic/releases/tag/0.78.0) onwards. However we recommend using latest release.

Here is the [documentation](https://specmatic.in/documentation/authentication.html#oauth2). I also recommend reading through our general [approach to authentication and authorisation in the contract of Contract Testing](https://specmatic.in/documentation/authentication.html#authentication-and-authorization-in-the-context-of-contract-as-test).

Here is a [sample springboot project](https://github.com/znsio/specmatic-order-api-java-with-oauth) for your reference.

Please do let us know your feedback and kindly log any fresh issues on the same.

cc @jaydeepk @joelrosario

**Comment by harikrishnan83** [comment]
@stijn-vanhoof-io @androa @kmichnie @dveljacic UPDATE: [Latest documentation on authentication](https://specmatic.in/documentation/authentication.html#testing-with-real-auth). Now you can also set bearer token, auth keys, etc. as per your security scheme through env variables.
