### ISSUE TITLE
An HTML response string is parsed as an XML object.

### ISSUE THREAD

**Issue by NazarBilous1** [specmatic/specmatic#621]
**Description**
If there is an HTML response in an API call, it will be processed as an XML object.

**Steps to reproduce**

1. Make an API request that returns HTML in the response Content-Type: text/html.
2. Create a contract for this API request.
3. Run this contract.
4. You may see something like this: Contract expected empty string but response contained <html><head><meta charset="UTF-8"/><meta content="0;url='https://google.com'" http-equiv="refresh"/><title>Redirecting to https://google.com</title></head><body>Redirecting to </body></html> (XML).

**Expected behavior**
If there is html response in API call, it will be processed like simple string.

**Additional context**
I thing that there is a problem in this code -> https://github.com/znsio/specmatic/blob/c19cf16cc285915c177e6a7b7998f273ec14d34e/core/src/main/kotlin/in/specmatic/conversions/Postman.kt#L224
Because application figure out what is the type by first char in string.
Maybe better use `Content-Type` for figure out what is the type and how need to handle it. If we don't have this header, we can figure out by first char

**Comment by jaydeepk** [comment]
Thanks @NazarBilous1 for reporting this.
We will have a look at this and get back to you.

**Comment by joelrosario** [comment]
Hi @NazarBilous1, we've just merged a fix for this, and it will be available soon in a new release.
