### ISSUE TITLE
AsyncApi Support

### ISSUE THREAD

**Issue by askenaz** [specmatic/specmatic#632]
Hi,

I can't find any documentation reference for AsyncApi support. Is it supported? 

Thanks in advance for your help.

Best regards,

-------------- 👆 Click "Preview"!

Issues on GitHub are intended to be related to problems with the library itself
and feature requests so we recommend not using this medium to ask them here 😁.

---

## ❓ Support Forums

For questions related to using the library, please visit a support community
instead of filing an issue on GitHub.

- Documentation: https://specmatic.in/documentation.html

**Comment by harikrishnan83** [comment]
hello @askenaz, Thanks for reaching out. AsyncAPI is currently in private beta. Can you please register your interest on our [contact us](https://specmatic.in/contact-us/) form? And we will keep you posted on this.
