### ISSUE TITLE
gRPC API support

### ISSUE THREAD

**Issue by plaird** [specmatic/specmatic#635]
**Is your feature request related to a problem? Please describe.**
From the product Goals section in the docs, it looks like it is intended to provide support for gRPC APIs:

[API calls (JSon REST, SOAP XML, gRPC, Thrift, other binary protocols)](https://specmatic.in/documentation.html)

But a further search of the documentation makes no other reference to gRPC, so it seems like this is a roadmap feature.

**Describe the solution you'd like**
It sounds like this is already a planned feature, so I won't document the details. 
Mostly creating this record so I (and others) can subscribe for updates.

**Comment by harikrishnan83** [comment]
@plaird Thanks for reaching out. We will keep you posted on this thread about gRPC support.

**Comment by Torchun** [comment]
@harikrishnan83 I can see it is no more on roadmap for 2024Q1 and further. Any updates?

**Comment by harikrishnan83** [comment]
@plaird @Torchun Appreciate your patience on this. We have released support for gRPC. Here is a sample project that demonstrates the capability.

[https://github.com/znsio/specmatic-order-bff-grpc-go](https://github.com/znsio/specmatic-order-bff-grpc-go)

Please have a look and let us know what you think. Closing the issue for now, however if you do have any feedback please do comment and / or re-open the issue. Thanks again for your interest.

**Comment by plaird** [comment]
Thanks Hari.
