### ISSUE TITLE
Support for asynchapi / messaging

### ISSUE THREAD

**Issue by bartoliniii** [specmatic/specmatic#657]
Hello!
Your project seems to be very promising, and I was excited when I saw that you support both opeanapi and asynchapi specifications. Unfortunately, I cannot find any examples of anychapi/messaging. Whenhen I try to use my asynchapi.yaml I got an error (in both JUnit and standalone approaches)

Could you please guide me, how spermatic can be used for contract-tests for asynch calls/messaging?

**Comment by harikrishnan83** [comment]
@bartoliniii Thanks for reaching out. We are currently in private beta for AsyncAPI support. Can you please share your contact information [here](https://specmatic.in/contact-us/) so that we can keep you posted on when AsyncAPI support will be generally available.

**Comment by harikrishnan83** [comment]
@bartoliniii We are glad to share the details about AsyncAPI support in our recent posts.
[AsyncAPI and Kafka](https://specmatic.in/updates/kafka-mocking-with-asyncapi-using-specmatic/)
[AsyncAPI and JMS](https://specmatic.in/updates/jms-mocking-with-asyncapi-using-specmatic/#gsc.tab=0)

Please do have a look and reach us if you have any questions on this. Closing this issue for now. Please feel free to re-open if you have any related items to discuss.
