### ISSUE TITLE
Parsing of authorization header is case sensitive

### ISSUE THREAD

**Issue by androa** [specmatic/specmatic#658]
When using bearer based authentication `specmatic` says it cannot find the `authorization` header. The [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) defaults to lowercasing all headers.

`specmatic` is case sensitive when looking at the headers, so `Authorization` works while `authorization` does not.

https://github.com/znsio/specmatic/blob/147c566959f4510d3dfa09dda8e0e69546e42278/core/src/main/kotlin/in/specmatic/conversions/BearerSecurityScheme.kt#LL11C36-L11C47

**Comment by harikrishnan83** [comment]
@androa thanks for reporting the issue. We are taking a look.

**Comment by androa** [comment]
A test case that simulates the behaviour

```
    @Test
    fun `getting headers by key should not be case sensitive`() {
        val request = HttpRequest(method = "POST", path = "/customer", headers = mapOf("authorization" to "Bearer token"))
        assertThat(request.headers.containsKey("Authorization")).isTrue
    }
```

**Comment by androa** [comment]
I guess the best solution here would be implementing a `CaseInsensitiveMap` like ktor uses here: https://github.com/ktorio/ktor/blob/e632bf5a943d44e1fb009bca8c5aa35d19bd6059/ktor-utils/common/src/io/ktor/util/CaseInsensitiveMap.kt#L10

**Comment by joelrosario** [comment]
Hi @androa, thanks for reporting this bug! We've just merged a fix for it to main, and it will be out with the next release.

**Comment by maoberlehner** [comment]
I think there is a regression here! I get `Header named Authorization in the stub was not found in the request` when sending a lower-case `authorization` header. Works when sending `Authorization`.
