### ISSUE TITLE
On marking a failing contract with @WIP tag, it still fails for backward compatibility check

### ISSUE THREAD

**Issue by deveshch** [specmatic/specmatic#66]

**Comment by deveshch** [comment]
The python script is using qontract-0.14.2-SNAPSHOT-2.jar.

**Comment by joelrosario** [comment]
Try with the latest, it shouldn't be an issue. You'll need to make the appropriate jar available to the build script.

**Comment by joelrosario** [comment]
This was a problem in an older version and was already fixed.
