### ISSUE TITLE
NullValue has a typo for httpContentType - 'text/pain'

### ISSUE THREAD

**Issue by jturnergresham** [specmatic/specmatic#681]
Very minor - quicker for you to fix than for a fork and PR:

object NullValue : Value, ScalarValue {
    override val httpContentType: String = "text/pain"

**Comment by jaydeepk** [comment]
Thanks a lot for reporting this @jturnergresham

**Comment by joelrosario** [comment]
Hi @jturnergresham, thanks for reporting this. The fix is done and will go out with the next release.
