### ISSUE TITLE
I don't seem to be getting generative tests with invalid values for path variables

### ISSUE THREAD

**Issue by jturnergresham** [specmatic/specmatic#682]
I don't seem to be getting generative tests with invalid values for path variables - it is working for my request body, but not for query params; are there any simple gotchas?

**Comment by jaydeepk** [comment]
Hi @jturnergresham 
Thanks for reaching out.
At present, the generative tests include only the request body and headers.

**Comment by jturnergresham** [comment]
Thanks Jay.
