### ISSUE TITLE
official container image for specmatic

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#683]
In order to run the specmatic in containerized CICD environments (like Gitlab), provide an official container image that is maintained and scanned for vulnerabilities.

**Comment by jaydeepk** [comment]
Thanks a lot for reaching out to us @kiranpatel11 .
We'll have a look at this and get back to you.

**Comment by joelrosario** [comment]
Hi @kiranpatel11,

We have recently published an official Specmatic Docker image which you can use for CICD environments. You can see examples of how it may be used in our [documentation](https://specmatic.in/getting_started.html).

Closing this for now, but please reopen if you have any followup questions.
