### ISSUE TITLE
Support Question: using Specmatic DSL as mocks/stubs 

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#685]
> Disclaimer: It is a support question, github issue creation hint to use the support channel for the same, but I could not really find any support channel information in your Github README, documentation or website 

- can the contract tests for provider written in specmatic DSL be used to setup the mocks/service-virtualization for consumers without having to configure json data files as documented in your ServiceVirtualization section?

**Comment by jaydeepk** [comment]
Hi @kiranpatel11 
Thanks for reaching out to us.
I'm not sure I understand you fully.
When you say "without having to configure json data files", are you referring to setting expectations on the Specmatic Stub?
If so, you can do something like this in gherkin (assuming the stub is running on port 9000) :
```
Scenario Outline: Product Search
    Given url 'http://localhost:9000/_specmatic/expectations'
    And request
      {
        "http-request": {
          "method": "GET",
          "path": "/products"
        },
        "http-response": {
          "status": 200,
          "body": [
            {
              "id": 1,
              "name": "Product1"
            }         
          ]
        }
      }
   When method post
   Then status 200
  ```
  Here we are setting an expectation on the '/products' endpoint to respond with  a specific response.
  
  It would help if you could please provide a concrete example of what you are trying to achieve.

**Comment by kiranpatel11** [comment]
Alright, I will try to explain.

The consumer-driven contract testing and frameworks like Spring Cloud Contract and Pact works as below
1.  The consumers write their expectations using Given-When-Then syntax.
2.  The consumer develop and do their component testing by mocking/stubing these expectations.
3.  To verify the consumers expectations are valid, these expectations are run as test cases on the provider implementation and results are used as evidence that the provider adheres to the agreed contract.

As you see, the same BDD-style Given-When-Then expectations play two roles :
1) mocks for consumers
2) tests for provider.

My question is how Specmatic DSL can be used the same way. Technically it is the exact same thing - BDD-style expectations - with only difference is Specmatic DSL is written by the provider.

Now it is possible that the consumer may only need a **subset of scenarios** for mocks created from the provider-writen Specmatic DSL or they may need more variations of the agreed schema....and they would write such expectations for themselves.

**Comment by kiranpatel11** [comment]
I think the example you shared above may do what I am expecting, but I would like to create a more realistic example.

what I am expecting the example to cover is 

In Specmatic DSL:
1. setting stub expectations (request/response)
2. assertions using the matchers for dynamic values.

with this setup, 
- the request-response combination will be used to facilitate stubs.
- the request-assertions combination will be used to verify provider implementation.


I did not find any information using the `matchers` in your documentation. something similar to https://docs.pact.io/getting_started/matching

**Comment by jaydeepk** [comment]
Hi @kiranpatel11 

At present, we do not have something like matchers.
Specmatic's DSL is based on Gherkin, so you'd get to do only all that's possible with gherkin.

Regarding your original question about "can contract tests for provider written in specmatic DSL be used to setup the mocks/service-virtualization for consumers" , this doesn't work quite like the way you're expecting it to.

Let's say we have a provider service and a consumer service.
The consumer service would need to know the open api specification of the provider service (ideally via a [specmatic.json](https://specmatic.in/documentation/specmatic_json.html) file).

As far as the provider service goes, there are two main things that Specmatic provides:

1. The ability to run contract tests for the provider service.
   In this, Specmatic will assert if the provider service satisfies its open api specification.
   This is called the Test mode.
   The contract tests for the provider are completely separate and isolated from the consumer tests.
   
2. The ability to stub out the provider service, (also known as Stub mode) when:
   a) Running contract tests for the consumer service (assuming there exists an open api specification for it)
   b) Running api tests for the consumer service (using say gherkin/karate) or component tests (using something like Junit)
   
   In this, Specmatic uses the provider's open api spec and creates an HTTP stub.
   You can set expectations on this stub as needed.
    If no expectations are set, Specmatic will use the provider's open api spec to generate responses (dummy data )for any requests that the stub receives.
    
    Hope this providers a better picture of how Specmatic works and is expected to be used.

**Comment by kiranpatel11** [comment]
> At present, we do not have something like matchers.
Specmatic's DSL is based on Gherkin, so you'd get to do only all that's possible with gherkin.

I am still not convienced with this answer. Karate is also inspired by the cucumber gherkin also and does support the matchers. 

I have created the issue for your sample project related to the same.
https://github.com/znsio/specmatic-order-ui/issues/2
It seems to be redundants to use multiple test frameworks (specmatic DSL and Karate) to achieve contract behavior verification.

**Comment by jaydeepk** [comment]
Hello @kiranpatel11 , thanks for taking the time to file the [issue](https://github.com/znsio/specmatic-order-ui/issues/2). This has helped us better understand the point of view from where you are coming. Let me clarify a few points.
* Matchers - Sorry looks like I misunderstood you here,  Specmatic does indeed support for matchers, please see - [https://specmatic.in/documentation/service_virtualization_tutorial.html](https://specmatic.in/documentation/service_virtualization_tutorial.html#accept-any-value-for-name-and-sku-and-return-a-random-id)
* Specmatic Gherkin DSL - Kindly refer to @harikrishnan83's [response](https://github.com/znsio/specmatic-order-ui/issues/2#issuecomment-1660052876) to understand the purpose of Specmatic Gherkin DSL

About your question 

> can the contract tests for provider written in specmatic DSL be used to setup the mocks/service-virtualization for consumers without having to configure json data files as documented in your ServiceVirtualization section?

Just to clarify, Gherkin DSL is not our primary / recommended way of represent API Contracts. In Specmatic API specs such as OpenAPI itself serves as executable API contract.

About below point you have mentioned in your [comment](https://github.com/znsio/specmatic/issues/685#issuecomment-1637222552).

> with only difference is Specmatic DSL is written by the provider

You seem to be bit mistaken here. Specmatic embodies Contract Driven Development (CDD) which is significantly different from Consumer Driven Contract Test.

Please do refer to our [comparison](https://specmatic.in/comparisons/specmatic-vs-pact-io-and-pactflow-io/) to better understand differences between Specmatic and Pact.

**Comment by kiranpatel11** [comment]
Thanks @jaydeepk and @harikrishnan83 for taking time to answer.

I will use this thread for covering the issue in that order-ui example repo.

@harikrishnan83 's answer does make sense, However, I would like to scratch a bit on the `executable contract` aspect.

1. What is API Contract ? 
It covers how API behaves and how it should be used. In technical terms, it covers the schema - data structure, endpoints, versioning - and behavior defined using the examples. 
2. Can OpenAPI specs covers all aspects of the API contract ?
Yes, It covers the schema aspect.
No, It does not cover the complete behavior aspects OOTB (without any custom extensions). Why it is so, because the coorelation between the particular request/response is not supported OOTB.
3. Does Specmatic address the above mentioned gap to define the API behavior ?
Yes, It smartly uses the `examples` key in OpenAPI specs and also provides DSL for improved readability for separating the examples. (awesome work by you guys).
4. Does it mean that Specmatic DSL + OpenAPI spec becomes `executable` contract tests **for the provider**? 
Well short answer is NO, but it does provide the foundation though.
Long Answer - The executable contract/testcases has to meet the characteristics of _repeatability and predictability_. Considering the typical testcase anatomy of - Arrange, Act, Assert - the Arrange step is used to meet these characteristics. There two things to be considered for the Arrange step.
 a. Setting up the input data that is visible/used in the contract (OpenAPI spec and/or Specmatic DSL).
 b. Setting up the external depedency based on the boundary of the subject-under-test (SUT). 
 Both the a) and b) involves a bit of internal implementation details of the SUT (white-box). Thats where your order-ui example uses the test framework like Karate. 
4. Does it mean that _Specmatic DSL+OpenAPI spec_ **of the provider** becomes `executable` stubs **for the consumer**? 
 Yes.
 I am also assuming, if the provider has SpecmaticDSL, then it can be used for the stubs as well. please confirm.
 In addition, It supports bring-your-own data for consumers using the json files and `/expectations` endpoint.
 (again, awesome work by you guys overall)
5. If the consumer-driven-contract-testing is desired (if the consumers and providers are evolving together), can the stubs created by the consumer be converted as contract tests for the provider ?
 At this moment, No.
 But thats something I would propose as a feature request. It may be implemented as just a _pact-adapter_ to fill the gap - if we decide to not reinvent the wheel.

Now my question/concerns is on the point#4, the glue required between the SpecmaticDSL and the test framework should only be for the _Arrange_ step. The Act and Assert steps should already be defined in the SpecmaticDSL and don't need to be repeated as in your order-ui karate tests. 

I hope this gives you the full context of what I am looking for.

**Comment by harikrishnan83** [comment]
@kiranpatel11  Thanks for taking the time to send us a detailed response. Appreciate it very much.

> What is API Contract ?
It covers how API behaves and how it should be used. In technical terms, it covers the schema - data structure, endpoints, versioning - and behavior defined using the examples.

In other words contract (in the contract as test context) encompasses structure and does not include internal implementation details / logic. Example: in a calculator API the fact the service takes two operands and an operation and returns a result may constitute the contract itself. Whether the calculation itself is correct or not is not relevant from a contract point of view.

Secondly the term contract also conveys the fact that it is enforceable on both parties. This is why OpenAPI or other API specifications by themselves are not API contracts. Only when they are made executable (as test on provider and as stub on consumer) we can consider them as contracts.

I suppose this also should clarify your question 2

About question 3, you are right.

Regarding question 4 there seems to a lot of different points you have mentioned. I will try to address some of them.
* OpenAPI is made executable contract by the fact that Specmatic is able to run it as a test on the provider and stub for consumer (this is unlike Pact where OpenAPI is a separate document that you maintain and the actual API contract there is Pact JSONs which is generated only by consumer application, even in Pactflow OpenAPI only serves as provider contract and not consumer contract).
* Karate framework serves a completely different purpose in the order-ui example. If you recall he calculator example which I shared above, Karate is verifying the logic aspect of whether the calculation 2 + 2 actually returns 4.
* With the above in mind I strongly believe that Specmatic does allow you to leverage OpenAPI as executable contracts

About question 5, just being clear on terminology, it is the contract that is executable (not the stub) which involves two pieces.
* Test for provider
* Stub for consumer

About question 6

> consumer-driven-contract-testing is desired (if the consumers and providers are evolving together)

At conceptual level Consumer Driven Contract Testing (CDCT) does not allow consumer and provider to evolve together. It is "Consumer First". Which means consumers need to be built first and in the process the mocks that are setup help generate the contract.

Contract Driven Development (CDD) and Specmatic in contrast truly allow parallel development of consumers and providers given the API contract is OpenAPI itself.

> can the stubs created by the consumer be converted as contract tests for the provider ?
At this moment, No.

This is incorrect, considering Specmatic is not biased either to the consumer (like Pact) or to the provider (like Spring Cloud Contract) there is nothing stopping you from adopting consumer first development style. In contract driven development if the consumer has to drive the development they define the OpenAPI and leverage it as a stub for their development purpose and eventually share that OpenAPI with the provider which serves as test for Provider. So there is no need to create a stub and then basis the stub create a contract. Hope this clarifies.

If you still have more questions and if it will be easier to have this conversation over a call, do reach us at [https://specmatic.in/contact-us/](https://specmatic.in/contact-us/).

cc @jaydeepk

**Comment by kiranpatel11** [comment]
specmatic as contract tests for provider is good.

but when I used specmatic for stubbing OAS, it does not use the example data provied in the OAS, everything is getting randomly generated even if the relevant example is present in the OAS.

I was expecting it to use the available data when present and generate the random data when not present

**Comment by harikrishnan83** [comment]
@kiranpatel11 The example data in the API specification as you rightly mentioned is only used for running tests on the provider. Since the stub data is usually the responsibility of the consumer application, that is exeternalised to expectation jsons. Please see [documentation](https://specmatic.in/documentation/service_virtualization_tutorial.html#fix-the-response-to-products10).

The reason for this design is because the stubs are largely owned and managed by each of the consumers and the tests on the other hand are better co-located with the API specification itself. However we have received some feedback to leverage the examples as stubs also. We are looking into adding this to our roadmap.

**Comment by kiranpatel11** [comment]
> However we have received some feedback to leverage the examples as stubs also.

Thats exactly was the primary question of this thread. It does create a coupling between consumer-provider using certain set of data, but at the same time, it does makes it convenient, as well as gives better assurance that the integration works as expected. In a way, thats becomes similar to OSS Pact, but the different would be consumer would have additional flexibility to configure their own stubs + it is provider-driven. In fact, you can consider having a flag for consumers to opt-in for this behaviour.

**Comment by harikrishnan83** [comment]
We will keep you posted on any changes in terms of possibility of leveraging examples for generating stub responses also.
