### ISSUE TITLE
Backstage plugin for specmatic

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#689]
## Context

[Backstage](https://backstage.io) is a extensible developer portal via plugin based architecture.
see the available plugins [here](https://backstage.io/plugins).

## Request

Consider the opportunity of creating Specmatic plugin for backstage so that it can be integrated with the ecosystem of tools.

How it may work:
Backstage already has api-doc plugin which helps to render the OAS using the Swagger UI. However, as known the Swagger UI may not be suitable for using the mockserver (does not support the request-response corelation). Specmatic can be used to compliment as mockserver to explore the API contract in more realistic way.

There would be potentially more usecases, but I think the above can be a good start.

**Comment by jaydeepk** [comment]
Thanks for this suggestion, we'll check it out and get back.

**Comment by jaydeepk** [comment]
HI @kiranpatel11, The support for Backstage is not in our road map at this point.
Thanks for suggesting the idea though, if anything changes on this front, we'll surely update you.
