### ISSUE TITLE
Compatibility with other stub-engines

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#694]
Few Questions related to the Specmatic stubs:

1. What specmatic uses under the hood for the stub-engine (e.g. Wiremock)?
2. does specmatic stubs adheres to the syntax of any popular tool like Wiremock for regex, dynamic fields?
3. Does it provide any migration tool from other stubbing tools ?

**Comment by harikrishnan83** [comment]
@kiranpatel11 Thanks for reaching out.

> What specmatic uses under the hood for the stub-engine (e.g. Wiremock)?

We have written our own stub. We do not user Wiremock. I encourage you to read through our codebase to understand the mechanics and details of the stub implementation.

> does specmatic stubs adheres to the syntax of any popular tool like Wiremock for regex, dynamic fields?

No. Specmatic expectation syntax at the moment is not designed to be interoperable with Wiremock.

> Does it provide any migration tool from other stubbing tools ?

Yes, you can import Postman collections, even plain reverse proxy logs to generate stubs.

Hope that helps.

**Comment by kiranpatel11** [comment]
@harikrishnan83 , the problem is - it is very hard to find information or reference about matches/regex syntax supported by the Specmatic in the documentation. 

e.g. 
How to assign the response fields from the request body or path or query param ? 
  `GET /pets/{petId}` when called with petId=123 should return the reponse body including `id:123`

some references from wiremock:
https://wiremock.org/docs/request-matching/
https://wiremock.org/docs/response-templating/

I wish the Specmatic would have not reinvented the wheel and only added missing capabilities - verifying the stubs against the OAS schema - to the wiremock via the extension.

**Comment by harikrishnan83** [comment]
@kiranpatel11 We are not re-inventing wheels. To answer your question, I am not even sure why you need to take a parameter from the request and return it in the body. You can simply have an expectation that exactly takes ```GET /pet/123``` and in response also has ```id:123```. In our experience having any logic or reference structures in expectations can be hard to read over time.

Also not sure what is your overall goal and what is the goal of your evaluation of Specmatic, if you could reach out to us on our website with the details, we would be more than happy to help.
