### ISSUE TITLE
How consumer knows that provider impl is conforming to the contract before code promotion ?

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#698]
Related issue #684 

Scenario:
1. Provider has published a new contract version not yet implemented/deployed to the integration env. Not PASSING yet.
2. Consumer, in anticipation of the new contract version, add new feature and completes its component tests. It PASSES. 
3. To avoid breaking the integration environment and avoid the consumer going ahead of the provider, how a consumer pipeline would know the deployed version of the provider in the integration env and its contract version is aligned with the version used by the consumer.

I have gone through the video links shared by @harikrishnan83  in #684 and the documentation, but such granular details are not clearly mentioned.

As an experienced developer, I can sense it can be implemented using git revisions/tags on a central contract repository or using something like PactMatric. But its better that the clarity is provided in your documentation about the code promotion guidelines to avoid such potential breakages. 

Another challenge I see in a complex enterprise scenario is to get everyone aligned on the have a central repository for the contract with shared access.

**Comment by harikrishnan83** [comment]
@kiranpatel11 Seems like these questions may be better answered over a call. Kindly reach out to us on our website and we will be happy clarify the same over a call.
