### ISSUE TITLE
Documentation missing on DataType matching in the stub json

### ISSUE THREAD

**Issue by harikrishnan83** [specmatic/specmatic#70]
I want to match any number for one or more of the request parameter in stub json so that I can get the same consistent stub response for some request parameters that change request to request.

**Comment by harikrishnan83** [comment]
Link to documentation https://qontract.run/documentation/service_virtualisation.html#datatype-matching-in-stubs

**Comment by joelrosario** [comment]
@harikrishnan83 This documentation was already there: https://qontract.run/documentation/service_virtualisation.html#stub-without-hardcoding-values-in-the-response

Could you deduplicate the docs on this. Thanks!

**Comment by joelrosario** [comment]
The original documentation might need to be expressed better / refactored / merged with this if it was not easy to discover.

**Comment by harikrishnan83** [comment]
@joelrosario Makes sense. I will merge these. Thanks for pointing this out.
