### ISSUE TITLE
open-api multiple files $ref for examples

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#702]
Specmatic not considering the examples references via $ref ?

#petservice.open-api.yaml
``` 
servers:
  - url: /
paths:
  /pets:
    post:
      summary: Create a new pet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
            examples:
              CREATE_PET_SUCCESS:
                $ref: "./create_pet_success.json"    #also tried with `value :` before this line, with no success. 
...
```

```
Junit5 test

        File apiContract = new File("src/main/resources/petservice.openapi.yaml");
        System.setProperty("contractPaths", apiContract.getAbsolutePath());
```

Observation:
Specmatic is not using the $ref example, but generating the random examples based on schema.

**Comment by harikrishnan83** [comment]
@kiranpatel11 apologies for the radio silence on this. We have a way to externalise test data as JSON. Here is the [documentation](https://specmatic.in/documentation/contract_tests.html#externalized-test-data). Hope this helps.

Please feel free to reopen the issue if you have any questions.
