### ISSUE TITLE
Reference documentation for Service Virtualization

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#705]
With the current documentation on the Service Virtualization(SV) it is not possible to understand how to handle the different dynamic values. Providing the reference for different data types and handling typical scenarios for SV would be useful.

Some examples below:
1. Mapping some of the fields from request to the corresponding response so that the users don't need to create and maintain 10s or 100s of stubs just to ensure such Ids are correlated for request/response. This is a very common usecase and supported by most established SV frameworks - microks, wiremock, mock-server, pact, karate etc. 
    e.g. Given a `GET /pets/{petId}` operation, when `petId=1`, the response should assign the id field with the same value to be useful in functional validation. 
2. For fields such as `created_timestamp`, `last_modified_timestamp` in the response payload, usually it is expected to return the timestamp of the executed request. How to do that using specmatic SV ?
3. How to generate the fields with typical fields like valid email, US SSN number, postcodes, phone numbers ? can you integrate with the popular faker library so that users don't have to deal with complexity of the regex for typical usecases?

Maintaining stubs over long time is challenging, and having some basic dynamic field mappings, generators reduces the need to maintain too many stubs. It does comes at the cost of reduced readability though, and its not recommended to overuse either. Having the balanced approach is usually the way to go.

PS: 
I raised similar question via other issue, but it got closed with the point answer for a specific example :-(
Please consider this issue as an overall improvement to the documentation and developer experience.

**Comment by harikrishnan83** [comment]
@kiranpatel11 these are some great points you have raised. Below are my responses.
* Point 1 - As explained earlier we are debating the need for this capability as the necessity for dynamism in the stub files may also be a smell of some other problem. I will get back to you on this shortly.
* Point 2 - Can you please explain what is the necessity for the same? Also if you are asserting on the exact values returned by the stub?
* Point 3 - This is valid and also already on our backlog of items. I will keep you posted on the availability of the same.

The points you have been raising are very valuable. Can you please bring these up in our [https://github.com/znsio/specmatic/discussions](https://github.com/znsio/specmatic/discussions) forum so that we can have a more detailed conversation on these points.

**Comment by kiranpatel11** [comment]
The important part of this thread is to consider the reference documentation for different options that can be used in SV.

- Point 2: The stubs are used by the consumers for the (slice) integration testing and component testing both. 
  
As suggested in [this article](https://martinfowler.com/articles/microservice-testing/#testing-integration-introduction), the integration testing is usually covers the layer of the integration code on consumer and the external service. In such kind of tests, the need for fields like `created_timestamp` or `modified_timestamp` to be logically accurate is not critical.

However, the component testing on the consumer side, expect the stubs to be as realistic as possible. Such fields may not be asserted individually in the tests, but their value may/maynot be used in the application logic and not having specific control may break the functionality. Also consider this is just an example, there can be other fields which may be driven by the execution time and may influence the application logic. 

The reusuability of the stubs across the tests is also the factor. Usually the stubs used in Component testing would be the subset of the stubs used in the integration testing (as per the above definition).

**Comment by kiranpatel11** [comment]
> The points you have been raising are very valuable. Can you please bring these up in our https://github.com/znsio/specmatic/discussions forum so that we can have a more detailed conversation on these points.

sure, I have created a thread in the `discussions`.

**Comment by harikrishnan83** [comment]
Discussion link - [https://github.com/znsio/specmatic/discussions/708](https://github.com/znsio/specmatic/discussions/708)

**Comment by joelrosario** [comment]
Closing this issue, since it has been moved to the discussions section.
