### ISSUE TITLE
Specmatic stub server does not start and returns contract violation

### ISSUE THREAD

**Issue by royshibu1975** [specmatic/specmatic#706]
**Description**

I have 3 OpenAPI specification files named as below

A) example1.yaml
B) example2.yaml
C) example_combined.yaml -> combined OpenAPI specification of A and B above 

When I try to start the Specmatic stub server with the individual files mentioned in A and B above the stub server starts successfully

But when I try to start the Specmatic stub server with the combined file (example_combined.yaml) it gives contract violation error

**Steps to reproduce**

1. The contents of the files mentioned in A, B and C are uploaded here https://www.dropbox.com/scl/fo/s9d1efbg182q42m8h6xcl/h?rlkey=jjbd36weh3kxtrbuymunuf1ai&dl=0

2. Run the below commands one by one
java -jar specmatic.jar stub example1.yaml  -> The Specmatic stub server starts successfully
java -jar specmatic.jar stub example2.yaml  -> The Specmatic stub server starts successfully
java -jar specmatic.jar stub example_combined.yaml  -> The Specmatic stub server does not start and returns contract violation as below

Loading example_combined.yaml
    Could not load /Users/sib.roy/Documents/Specmatic-ContractTest-Lending/lending-gateway/component-test/src/test/resources/example_combined.yaml: In scenario "Example 1. Response: Example 1."
API: POST /v1/arrangements -> 201

  >> REQUEST.BODY
  
     >> param4
   
        Key named param4 in the contract was not found in the row value
   
     >> param5
   
        Key named param5 in the contract was not found in the row value
   
     >> param6
   
        Key named param6 in the contract was not found in the row value
   
     >> param7
   
        Key named param7 in the contract was not found in the row value
   
     >> param1
   
        Key named param1 in the row value was not in the contract Could not find any HTTP contracts, so stub server not started.

**Expected behavior**

Specmatic stub server to start successfully with the combined OpenAPI specification file (example_combined.yaml)

**Screenshots**
The output contract violation error is mentioned above.

**System Information:**
 - OS & version: Mac OS 13.5.1
 - Specmatic version: 0.72.0
 - JDK version: 17

**Comment by harikrishnan83** [comment]
@royshibu1975 Thanks for reaching out. Not sure what you mean when you are saying that example_combined is created by combining API specifications example1 and example2. Because all these files have a single path and only differ in terms of the examples you have added.
* example 1 has GOOD_REQUEST_201
* example 2 has ANOTHER_GOOD_REQUEST_201

The issue may be that you are mixing up the examples in example_combined. The names need to match so that Specmatic can correlate the data cross your various parameters and response code.

Can you please share some more details about why are combining two specifications and the reason the examples seem to be mixed up in example_combile file?

**Comment by royshibu1975** [comment]
Hi @harikrishnan83 thanks for your response. I am not combining the 2 specifications (example 1 and example 2). I had only 1 specification (example_combined) to start with. When I faced the issue to load the stub with the specification (example_combined) I split the specifications into 2 (example 1 and example 2) and the stub started properly with example 1 and example 2 respectively.

Although the path is the same for example 1 and example 2 below is the difference

example 1 has below

content:
     application/vnd.10x.example1.v1+json:
          schema:
              $ref: "#/components/schemas/RequestSchema1" 

example 2 has below

content:
    application/vnd.10x.example2.v1+json:
         schema:
              $ref: "#/components/schemas/RequestSchema2"

The example_combined has got both the contents and schemas as below

content:
     application/vnd.10x.example1.v1+json:
          schema:
              $ref: "#/components/schemas/RequestSchema1"
     application/vnd.10x.example2.v1+json:
          schema:
              $ref: "#/components/schemas/RequestSchema2"

Please see the example_combined file for the examples I have written. Can you please have a look and throw some light what may be the issue with the examples in example_combined file. It looks all OK to me. Moreover when I split the file (example 1 and example 2 it all works fine individually)

Please see the RequestSchema1 and RequestSchema2. Both of them has a common internal schema CommonRequest with param2 common.

**Comment by joelrosario** [comment]
Hi @royshibu1975, sorry for the radio silence.

If you try the latest version of Specmatic (1.2.17), the stub server will start even for the combined spec.

Also, note that in all 3 specifications, `param3` in the response examples is not in fact in the response, though it is in the required list in the response. If you fix this, the stub will load the specifications without errors.

**Comment by joelrosario** [comment]
I am closing this for now, but please feel free to reopen this if you have followup questions.
