### ISSUE TITLE
Qontract hangs when contract file extension is wrong or contract file is missing

### ISSUE THREAD

**Issue by harikrishnan83** [specmatic/specmatic#71]
**Describe the bug**
When I run Qontract Stub Command with a non-existent contract file or a contract file with a mis-spelled extension name, the command does not give me any feedback, it simply hangs and I have Ctrl + C it.

**Steps to reproduce**
1. Download latest version 0.17.0
2. Run below command
```
java -jar qontract.jar non-existent-file.txt
```
3. There is not feedback

**Expected behavior**
1. In the scenario when the file is missing I want to see error message.
2. When extension is wrong, I have to get a suitable error message.
3. The command should exit with error code 1.

**Screenshots**
NA

**System Information:**
 - Mac OSX Catalina 15
 - Qontract version 0.17.0
 - JDK 11

**Additional context**
NA

**Comment by masaldaan** [comment]
I can take a stab at this.

**Comment by harikrishnan83** [comment]
> I can take a stab at this.

Please go ahead. Thanks for volunteering.
