### ISSUE TITLE
Contract test coverage report does not show which APIs are not covered by Contract test

### ISSUE THREAD

**Issue by royshibu1975** [specmatic/specmatic#710]
**Description**
I have enabled the gateway under management in application.yml file. Also downloaded the dependency org.springframework.boot:spring-boot-starter-actuator. When i run my Contract as test with my application context I can see the final report only shows the API coverage by the Contract test. I am expecting it to show the APIs which are not covered by the Contract as test as well. The details steps are given below 

**Steps to reproduce**

Please see the details here https://www.dropbox.com/scl/fi/zo78n3yo62p3x6xcqgm9x/API-Coverage.docx?rlkey=tqv4kobvwokih7geqcmg6l2tn&dl=0

**Expected behavior**
I expect in the API coverage report shall also show the APIs which are not covered by the Contract test.

**Actual behavior**
I can see in the report only shows the APIs which are covered by the Contract test.

**Screenshots**
All the screenshots are given in the document given here https://www.dropbox.com/scl/fi/zo78n3yo62p3x6xcqgm9x/API-Coverage.docx?rlkey=tqv4kobvwokih7geqcmg6l2tn&dl=0

**System Information:**
OS & version: Mac OS 13.5.1
Specmatic version: 0.72.0
JDK version: 17

**Comment by harikrishnan83** [comment]
@royshibu1975 Thanks a lot for the details. This is really helpful. We are taking a look and will keep you posted on the progress.

**Comment by jaydeepk** [comment]
@royshibu1975 , Thanks for reaching out to us.
Based on the snapshots that you have shared, it looks like you have set the `endpointsAPI` property to:
```
http://localhost:9393/gateway/routes
```
While this endpoint does list the routes in the application, the response schema is different from what Specmatic expects.
Hence Specmatic is unable to read the application routes and report them in the API Coverage report.

Specmatic expects the routes to be available in the schema based on [Spring Actuator's mappings endpoint](https://docs.spring.io/spring-boot/docs/current/actuator-api/htmlsingle/#mappings)

Could you please instead set the `endpointsAPI` property to the 'mappings' endpoint and try again?
```
System.setProperty("endpointsAPI", "http://localhost:9393/actuator/mappings");

```

We have recently made some enhancements to  the API Coverage Report.
[Here's](https://specmatic.in/updates/detect-mismatches-between-your-api-specifications-and-implementation-specmatic-api-coverage-report/#gsc.tab=0) a detailed write up regarding the same. Please do check it out.

Also it looks like you may not be using the latest version of Specmatic.
Please do try out our latest version `0.76.0` to be able to access the new features.

**Comment by jaydeepk** [comment]
@royshibu1975, please also ensure that the 'mappings' endpoint is enabled in your application.yml file:
```yaml
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info", "loggers", "gateway", "metrics", "mappings"]
```

**Comment by sgkiokas** [comment]
@jaydeepk I can confirm that the above is working as expected - @royshibu1975 confirmed as well. Thanks a lot for your guidance! I think you could close that ticket.

**Comment by jaydeepk** [comment]
Thanks @sgkiokas , @royshibu1975. Glad we could help.
