### ISSUE TITLE
Scenario matching error when API schema uses path param overloading

### ISSUE THREAD

**Issue by matus-m** [specmatic/specmatic#717]
**Description**
API schema path param overloading causes matching issue when two endpoints match request pattern - `/users/me` vs `/users/{userid}`

**Steps to reproduce**
1. create the following -valid - openapi schema that defines 2 endpoints, where the `v1/users/me` is an ,,overload" of the parametrized `v1/users/{userId}`
```yaml
openapi: 3.0.1
info:
  title: test case
  version: "1"
servers:
  - url: https://test.com

paths:
  /v1/users/me:
    get:
      operationId: getCurrentUser
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /v1/users/{userId}:
    get:
      operationId: getUserById
      parameters:
        - name: userId
          schema:
            type: number
          in: path
          required: true
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
```

For context, the `/v1/users/me` is for clients to get their current user, `v1/users/{userId}` would be for admin users to get arbitrary user by id.

2. Create a scenario in gherkin spec file:
```gherkin
Feature: Hello world

Background:
  Given openapi openapi/conflict.yaml            

Scenario: should get current user
  When GET /v1/users/me
  Then status 200
```
3. Run the tests - specmatic will fail with 1 of these 2 errors:

A: if the type of the ,,magic string" constant (in our case `me`) matches the type of the path pattern (in our case `{userId: string}` then the following error is thrown:
```
ContractException(errorMessage=Scenario: should get current user is not specific, it matches 2 in the included Wsdl / OpenApi, breadCrumb=, exceptionCause=null, scenario=null, isCycle=false)
``` 

B: if the type of the constant is different than the path pattern (as in the schema above, string vs number) then the following error is thrown:
```
ContractException(errorMessage=Error matching url /v1/users/me to the specification, breadCrumb=, exceptionCause=ContractException(errorMessage=Expected number, actual was "me", breadCrumb=, exceptionCause=null, scenario=null, isCycle=false), scenario=null, isCycle=false)
```

**Expected behavior**
Specmatic should recognise, that the scenario exactly matches one of the defined API endpoints and proceed to test it without issues.

The matching logic should be enhanced to correctly handle priority of matching results. In case B the tool could log warning for the mismatched pattern vs constant value, as long as we actually got a valid exact match. 
For case A, the matching scenario login in `Feature.kt` should be enhanced to not fail if there is an exact match among the results.

**Comment by joelrosario** [comment]
Hi @yntelectual, thanks for reporting this bug! The fix has been implemented, and it will be out with the next release.
