### ISSUE TITLE
Date-time strings do not contain offset part

### ISSUE THREAD

**Issue by matus-m** [specmatic/specmatic#721]
**Description**
As per https://datatracker.ietf.org/doc/html/rfc3339#section-5.6 which is the notation mandated by openapi's `date-time` format, the date time strings should always contain timezone offset part. 
Specmatic generates date-time strings without offset information: e.g. `2023-09-01T14:37:25.347356`

**Steps to reproduce**
1. define a parameter of type date-time:
```yaml
schema:
  type: string
  format: date-time
```
2.run tests

**Expected behavior**
A valid RFC 3339 date-time string should be generated (for example by appending `Z` at the end or by appending time offset based on current TZ)

**Comment by attard-divido** [comment]
I am encountering the same problem myself. I use the OpenAPI [go generator](https://openapi-generator.tech/docs/generators/go) to generate a client SDK and it will parse the generated `date-time` values with the [`time.RFC3339`](https://pkg.go.dev/time#pkg-constants) by default.

I tried to look for a way to tell specmatic what value to generate for that one field but it seems that expectations can only be set at the request-response level.

**Comment by harikrishnan83** [comment]
@yntelectual Thanks for reporting the issue. It is indeed a good issue to address. We are bumping this up in our backlog.

**Comment by harikrishnan83** [comment]
@attard-divido Thanks for adding to this thread. Can you please elaborate if you are running your OpenAPI specifications as test or as stub?

**Comment by attard-divido** [comment]
> @attard-divido Thanks for adding to this thread. Can you please elaborate if you are running your OpenAPI specifications as test or as stub?

Thank you for your reply. I've only tried OpenAPI spec as stub for now. I cannot comment on OpenAPI spec as test for now.

**Comment by harikrishnan83** [comment]
@yntelectual @attard-divido @DapperMongoose Thank you for your patience on this. We have fixed this issue and the same should be part of our upcoming release. cc @jaydeepk @joelrosario
