### ISSUE TITLE
204 responses are always ignored in coverage

### ISSUE THREAD

**Issue by matus-m** [specmatic/specmatic#722]
**Description**

Endpoint responses with status 204 are reported as not covered by the OpenApi report - even though the scenarios are generated and executed by specmatic. Response definitions with status 204 do not have any body schema that we can attach examples to, and Specmatic will ignore request param examples without matching response examples. In the case of the schema bellow, Specmatic will ignore the `204_OK` example value and generate a scenario with random string value. The testcase is executed without error, but the resulting coverage report will report this endpoint as not covered (the scenario is marked as Skipped due to missing examples...)

**Steps to reproduce**
1. Given a simple schema with 204 response:
```
openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /api/nocontent:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: string
            examples:
              204_OK:
                value: "hibob"
      responses:
        204:
          description: No content
```
2. run the specmatic test with this schema as source

**Expected behavior**
Specmatic should execute a request based on the request param example specified and simply assert status returned and no body. 

Test output:
```
--------------------
  Request to http://localhost:56102 at 2023-9-5 3:25:27.284
    POST /api/nocontent
    Accept-Charset: UTF-8
    Accept: */*
    
    IGFIB

  Response at 2023-9-5 3:25:27.285
    204 No Content
    Date: Tue, 05 Sep 2023 13:25:27 GMT
    Keep-Alive: timeout=60
    Connection: keep-alive
    
    

|-------------------------------------------------------------------------------|
| API COVERAGE SUMMARY                                                          |
|-------------------------------------------------------------------------------|
| coverage | path           | method | response | # exercised | remarks         |
|----------|----------------|--------|----------|-------------|-----------------|
|       0% | /api/nocontent | POST   |      204 |           0 | missing in spec |
|-------------------------------------------------------------------------------|
| 0% API Coverage                                                               |
|-------------------------------------------------------------------------------|
1 out of 1 endpoints are not completely covered in the specification.
```

**Comment by matus-m** [comment]
Just to clarify, this is not linked to the status itself, merely to the absence of response body - which is common for 202, 201 responses as well. I believe the correct behavior in such case would be to define the scenarios based on request param/body examples.

**Comment by harikrishnan83** [comment]
@yntelectual Thanks for reporting this. We will look into possible ways to address such response codes. Meanwhile here is a workaround if you are okay with adding a schema to the response section (we know it is not ideal). I tested below sample with a Springboot application that returns a 204 NO_CONTENT.

```yaml
openapi: 3.0.3
info:
  title: My service
  description: My service
  version: 1.0.0
servers:
  - url: 'https://localhost:8080'
paths:
  /api/nocontent:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            examples:
              204_OK:
                value: {"name": "hibob"}
      responses:
        204:
          description: No content
          content: 
            text/plain:
              schema:
                type: string
              examples:
                204_OK:
                  value: 
```

**Comment by yogeshnikam671** [comment]
The API coverage is now covering 204 scenarios even without an example.
```
|-----------------------------------------------------------------------------|
| API COVERAGE SUMMARY                                                        |
|-----------------------------------------------------------------------------|
| coverage | path                 | method | response | # exercised | remarks |
|----------|----------------------|--------|----------|-------------|---------|
|     100% | /products            | GET    |      200 |           1 | covered |
|          |                      | POST   |      200 |           1 | covered |
|     100% | /products/no-content | POST   |      204 |           1 | covered |
|-----------------------------------------------------------------------------|
| 100% API Coverage reported from 2 paths                                     |
|-----------------------------------------------------------------------------|
 ```

What you have reported is resolved. Although while testing this, we came across a related [issue](https://github.com/znsio/specmatic/issues/1063). That will be fixed separately.

Closing this one. If you have any other questions on this, please feel free to reopen.
