### ISSUE TITLE
write coverage report to file

### ISSUE THREAD

**Issue by matus-m** [specmatic/specmatic#723]
**Is your feature request related to a problem? Please describe.**

It would be great if Specmatic could produce a dedicated report file with API coverage report - so that we could surface it as a build artifact in CI.

**Describe the solution you'd like**

Add a new report formatter  and corresponding config options to enable it, for example:
```
"report": {
    "formatters": [
      {
        "type": "text",
        "layout": "table"
      },
    {
        "type": "file",
        "layout": "table",
       "name" : "my_coverage_report.txt"
      }
    ],
```

**Describe alternatives you've considered**
We could extract the report section out of the test stdout, but its cumbersome.

**Comment by harikrishnan83** [comment]
@yntelectual Thanks again. This is already on our backlog. Will keep you posted.

**Comment by joelrosario** [comment]
Hi @yntelectual, Specmatic publishes the API Coverage Report to a file (`build/reports/specmatic/coverage_report.json`). We have documented this [here](https://specmatic.in/documentation/contract_tests.html#api-coverage).

Closing this for now. But please reopen it if you have followup questions.
