### ISSUE TITLE
Omit git references from specmatic config

### ISSUE THREAD

**Issue by sgkiokas** [specmatic/specmatic#724]
Hi guys,

I have setup Specmatic locally and it works perfectly fine if I configure it to use my specs which are loaded remotely to Bitbucket. If I omit the git-related references I, correctly, get 

```
SpecmaticContractTest > initializationError FAILED
    java.lang.ExceptionInInitializerError
```
Looking at your code, this is exactly what it should happen.

My main question/request is to have the capability to fetch specs to be stubbed only from our local workspace without the need of remotely connecting to any repo. Maybe, this is by design or I even missed this in your documentation, but I think having this capability would be useful if you hook Specmatic in a CI environment in which `git` is not the case.

An example of the current config is:

```
{
  "sources": [
    {
      "provider": "git",
      "repository": "myRepo.git",
      "branch": "myFeatureBranch",
      "stub": [
        "external/myspecs.yaml"
      ]
    }
  ],
  "report": {
    "formatters": [
      {
        "type": "text",
        "layout": "table"
      }
    ],
    "types": {
      "APICoverage": {
        "OpenAPI": {
          "successCriteria": {
            "minThresholdPercentage": 70,
            "maxMissedEndpointsInSpec": 3,
            "enforce": true
          }
        }
      }
    }
  }
}
```

I was thinking something along the lines of:

```
{
  "sources": [
    {
      "stub": [
        "external/ambassador/lendinggateway.yaml"
      ]
    }
  ],
  "report": {
    "formatters": [
      {
        "type": "text",
        "layout": "table"
      }
    ],
    "types": {
      "APICoverage": {
        "OpenAPI": {
          "successCriteria": {
            "minThresholdPercentage": 70,
            "maxMissedEndpointsInSpec": 3,
            "enforce": true
          }
        }
      }
    }
  }
}
```

**Comment by harikrishnan83** [comment]
@sgkiokas Thanks again for reaching out. This is already in our backlog. We will keep you posted on the progress. cc @vikram-rao

**Comment by joelrosario** [comment]
Hi @sgkiokas,

Specmatic now supports loading specifications from the local file system. You can read more about it in our [documentation](https://specmatic.in/documentation/specmatic_json.html#use-specifications-on-local-file-system).

Closing this for now. Please reopen if you have any followup questions.
