### ISSUE TITLE
specmatic standalone jar in maven central repository

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#731]
Currently below specmatic jars are published to the maven central repository.

- `specmatic-core`
- `junit5-support`

Can we also published the standalone/executable jar `specmatic.jar` to the maven central as part of the publish workflow ?

The reason for the request is 
- If the standalone jar is available in the maven central, then it can be downloaded with below mvn command:
`mvn dependency:copy -Dartifact=in.specmatic:specmatic:VERSION:jar -DoutputDirectory=.`
This is useful in the CI envs (like ours) where the arbitrary HTTP download endpoints (like github) are restricted, and only internal proxy registries are used for public dependencies, with some sort of artifact scanning for security. 

- in some cases, it may also help to run specmatic standalone using the maven

**Comment by joelrosario** [comment]
Sounds like a valid use case. The only concern we've had is the size of our shadow jar. Can you please share which CI pipeline product you use? If it's Github, there's a [community-contributed Github action](https://github.com/marketplace/actions/setup-specmatic-environment) for setting up a Specmatic environment.

**Comment by kiranpatel11** [comment]
We have self-hosted Bamboo and planning to migrate to self-hosted GitLab.

**Comment by kiranpatel11** [comment]
@joelrosario , let me know if you planning to consider this request for implementation and can prioritize it as well.

**Comment by kiranpatel11** [comment]
> Sounds like a valid use case. The only concern we've had is the size of our shadow jar. Can you please share which CI pipeline product you use? If it's Github, there's a [community-contributed Github action](https://github.com/marketplace/actions/setup-specmatic-environment) for setting up a Specmatic environment.

Given the size of the shadow jar, its even better to cache it in organizations internal repositories like nexus, rather than downloading from github releases everytime. may be another reason to push to the maven central.

Github releases can also be configured as proxy, similar to the maven-central, but unfortunately for us that is not an option at this stage.

**Comment by joelrosario** [comment]
@kiranpatel11 we've addressed this. In the next release, the Specmatic standalone jar will be found in the maven central repository.
