### ISSUE TITLE
specmatic api coverage report location

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#732]
Currently the coverage report is generated at `{project-root}/build/reports/specmatic/coverage_report.json`

Shouldn't the api coverage report generated with `specmatic-core` and `junit5-support` libraries be somewhere under the `target` folder ?

**Comment by joelrosario** [comment]
Hi @kiranpatel11 , for maven it could be target, for gradle it could be build, and for node / python there would be others.

We're starting off with `{project-root}/build/reports/specmatic/coverage_report.json` for now as we are in the early stages of building this out, and it will soon be configurable.

Is the question answered? Or is there something else you're looking for?
