### ISSUE TITLE
Problems while importing postman exports and swagger files.

### ISSUE THREAD

**Issue by shray-sharma-phrase** [specmatic/specmatic#741]
Hey guys, our company has gone through your product and we think it is amazing and brings immense value. 
its a great idea and we love your product.
However we are having issues setting it up,
We have a postman extract and tried to import it, following your documentation.
But sadly we end up with an error "Expected an xml node: 
   This page has moved. Click" 
   
   and the process just terminates. we are unable to understand where does this issue point to and what has to be fixed.
   
   Alternatively, we have tried using our API documentation as a contract but , it is in swagger , and i guess you guys do not support that right?
because we end up in a situation where it says 0 tests run 
0fail 0 succesful...

we are unable to understand the issue why no tests are being run/generated.

our API documentation:
https://cloud.memsource.com/web/internal/v1/docs/latest/yaml?internal=false

Also, do you guys offer services for helping setup your product?

**Comment by joelrosario** [comment]
Hi @shraysharmaphrase,

> Hey guys, our company has gone through your product and we think it is amazing and brings immense value. its a great idea and we love your product. 

I'm glad to see that the product resonates with your team!

> However we are having issues setting it up, We have a postman extract and tried to import it, following your documentation. But sadly we end up with an error "Expected an xml node: This page has moved. Click"
> 
> and the process just terminates. we are unable to understand where does this issue point to and what has to be fixed.

I wonder if you're able to share the terminal / command prompt log of the Postman conversion. Can you also share which version of Postman you are using? Specmatic supports Postman 2.1.

> 
> Alternatively, we have tried using our API documentation as a contract but , it is in swagger , and i guess you guys do not support that right? because we end up in a situation where it says 0 tests run 0fail 0 succesful...
> 
> we are unable to understand the issue why no tests are being run/generated.
> 
> our API documentation: https://cloud.memsource.com/web/internal/v1/docs/latest/yaml?internal=false

WIth respect to specification format, Specmatic supports OpenAPI 3.0.x. On that note, I see the API specification format at the link you've shared is Swagger 2.0. You should be able to use https://editor.swagger.io to convert it to OpenAPI 3.0.x. Hope that helps.

> 
> Also, do you guys offer services for helping setup your product?

Yes, we'd be happy to help. You can drop us a line using the contact page at https://specmatic.in/contact-us/ with a link to this issue for context.

**Comment by shray-sharma-phrase** [comment]
Load Error FAILED
Reason: Specmatic only supports bearer and api key authentication (header, query) security schemes at the moment



Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: Specmatic only supports bearer and api key authentication (header, query) security schemes at the moment
        
        
        thank you for your help, i am getting the above error after sucessful conversion to openAPI.
        
        do you think , its a problem with the authentication modes supported by specmatic or is it some issue on my side? if you think this issue can be fixed we can jump on a call.

**Comment by harikrishnan83** [comment]
@shraysharmaphrase Thanks for sharing the error. We can jump on a call and take a look. I have responded to your message on our contact form and requested for a time for scheduling the call. Can you please check and know a time as per your convenience? cc @joelrosario @vikram-rao

**Comment by harikrishnan83** [comment]
@shraysharmaphrase since we have already discussing this over email, I am closing this issue. Please feel to re-open and / or report other issues as needed. Thanks.
