### ISSUE TITLE
AnyPattern handling of nullable data

### ISSUE THREAD

**Issue by aeoncl** [specmatic/specmatic#742]
**Description**
When you have an endpoint that returns an array of JSON data that can also be nullable. The generation of data fails and you get an exception in the AnyPattern class

This is because the AnyPattern class doesn't handle nullable fields correctly

**Steps to reproduce**
1. Given the following openapi contract: 
```yaml
openapi: 3.0.3
info:
  contact:
    url: http://balbala
  title: MyFileRestAPI
  description: A file rest api
  version: 1.0.0
servers:
  - url: "http://{hostname}:{port}/{basePath}/"
    variables:
      hostname:
        default: localhost
      port:
        default: "8080"
      basePath:
        default: rest
  - url: "http://localhost:9000"
tags:
  - name: importantstuff
paths:

  "/importantstuff/{id}/status":
    get:
      tags:
        - importantstuff
      operationId: getImportantStuffStatus
      parameters:
        - in: path
          name: "id"
          description: "id"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "List of important stuff status"
          content:
            application/json:
              schema:
                type: object
                title: Response
                properties:
                  errorMsg:
                    type: string
                    nullable: true
                  data:
                    nullable: true
                    type: array
                    items:
                      type: object
                      nullable: true
                      title: ImportantStuffStatus
                      properties:
                        type:
                          type: string
                          minLength: 1
                        flag:
                          type: boolean
                        sentDate:
                          type: string
                          format: date-time
                        document:
                          type: string
                          minLength: 1
                          nullable: true
                      required:
                        - type
                        - flag
                        - sentDate
                        - document
```
2. Run specmatic in stub mode: specmatic stub myamazingapi.yaml
3. Make an http request looking like this: GET http://localhost:9000/importantstuff/1/status
 
You need to try the request a few times to encounter the bug, the RNG decides between generating a NullPattern & the AnyPattern

**Expected behavior**
I expect Specmatic to generate the data without crashing

**Screenshots**
![image](https://github.com/znsio/specmatic/assets/48886723/3ced1a99-d450-4504-8693-7c29c4b9aa99)

**System Information:**
 - OS & version: Windows 11
 - Browser & version: Insomnia 2023.5.8
 - Specmatic version: 0.76.0
 - JDK version: OpenJDK 17

**Comment by joelrosario** [comment]
Thanks @aeoncl for reporting this. Looks like a bug, and we were able to reproduce it using the specification you've shared.

Happy to accept a PR if you happen to have the time :-)

**Comment by aeoncl** [comment]
Hehe already made the PR !
