### ISSUE TITLE
Externalizing examples in the .spec file doesn't appear to allow linking to concrete response examples?

### ISSUE THREAD

**Issue by markgargan** [specmatic/specmatic#745]
Hi folks, loving the framework! Am really hoping it's going to be a viable option for replacing our Spring Cloud Contract tests. I've an openapi yml spec for a quotation system we're building out. I can explicitly provide Request/Response pairs in the Examples section under the Schema, however, when I attempt to externalize these, it appears I can only externalize the requests. Providing Response Examples doesn't appear to be possible in the spec file in such a way that the requests produced in the Examples would marry up with the Response Examples. 

  Scenario Outline: Create Quote
    When POST /quot1
    Then status 200
    Then response
    Examples:
      | quoteReference        | customers |
      | VALID_QUOTE_REFERENCE | [{"type": "A", "dateOfBirth": "2023-01-01"}, {"type": "B", "dateOfBirth": "2022-01-01"}]|
    Response Examples:
       | fullPrice | monthlyPrice | status |
       |     10      |         20          |    OK   |

**Comment by joelrosario** [comment]
Thanks for raising this @markgargan. We'd love more participation on this topic. Moving to discussions.
