### ISSUE TITLE
Externalizing the request/responses into the _data folder json files for provider tests

### ISSUE THREAD

**Issue by markgargan** [specmatic/specmatic#746]
In the example on youtube provided here https://www.youtube.com/watch?v=gujV8NyMBEs&ab_channel=ConfEngine&t=28m09s, Joel appears to externalize the request/response pairs to a json file in the product-api_data folder. Is this possible to do with the API provider tests in Java.
I have a ContractTest that extends the SpecmaticJunitSupport class and I specify the contractsPath as 

    System.setProperty("contractPaths", "src\\test\\contracts\\quotes-api.yaml");

however, when I provide say a happy_path.json file in a folder quotes-api_data at the same level as the quotes-api.yaml file, specmatic doesn't appear to pick it up when running the API tests. Is this only available when stubbing tests? 

Thanks,
Mark.

**Comment by joelrosario** [comment]
Hi @markgargan,

Looks like you're trying to separate the test data from the OpenAPI specification. Specmatic can externalise test data [as shown here](https://specmatic.in/documentation/contract_tests.html#externalising-examples--test-cases).

The expectation JSON files serve a different purpose, and as you rightly pointed out, is used only during stubbing. We are also building an alternate implementation and will keep you posted on this.

Meanwhile, does this work for you?

**Comment by markgargan** [comment]
Hi Joel, 

Yes this is almost working perfectly. I have a .spec file that references the openapi yaml. I've removed all Examples from the openapi spec file. I reference the .spec file as a contractsPath in the setup method of my ContractTests which extends the SpecmaticJunitSupport class. When I run it, it successfully swaps in the customerReference in the right place and it creates a single Customer in the 'customers' list and replaces the dateOfBirth value. However, the 'And response-body expectedResponse' doesn't check the response against the json object in the Examples column even though there's examples of this in the language.html file located at https://specmatic.in/documentation/language.html

I have the following table in the spec. 
```
  Scenario Outline: Valid Customer
    When POST /customer
    Then status 200
    And response-body expectedResponse
    Examples:
      | customerReference                    | dateOfBirth  | expectedResponse                                                         |
      | VALID_CUSTOMER_REFERENCE | 2025-01-01  | "{'fullPrice': '10.0', 'monthlyPrice': '20.0', 'customerStatus' : 'OK'}" |
```
A valid Customer POST looks like 
```
{
	"customerReference": "VALID_CUSTOMER_REFERENCE",
	"customers": [
		{
			"customerType": "A",
			"dateOfBirth": "2023-01-01"
		},
		{
			"customerType": "B",
			"dateOfBirth": "2022-01-01"
		}
	]
}```

**Comment by markgargan** [comment]
Ideally what I would like to do is to define a Customer Type with different customers that I could then reference in a customers column in the Examples table picking the customers to be in the array on the basis of the id in the table. Do you know if this is possible Joel? I found the gherking docs to be a little light on the ground wrt to the Examples sections 

```

  Scenario Outline: Valid Customer
    Given type Customer
      | id | customerType | dateOfBirth |
      | 1  | A            | 2021-01-02  |
      | 2  | B            | 2020-01-02  |
      | 3  | C            | 2019-01-02  |
      | 4  | D            | 2018-01-02  |
    When POST /customer
    Then status 200
    And response-body expectedResponse
    Examples:
      | customerReference                | customers                  | expectedResponse                                                         |
      | VALID_CUSTOMER_REFERENCE         | [Customer(1), Customer(2)] | "{'fullPrice': '10.0', 'monthlyPrice': '20.0', 'customerStatus' : 'OK'}" |
      | ANOTHER_VALID_CUSTOMER_REFERENCE | [Customer(3), Customer(4)] | "{'fullPrice': '20.0', 'monthlyPrice': '30.0', 'customerStatus' : 'OK'}" |
    
```

**Comment by joelrosario** [comment]
@markgargan given that we are discussing this [in the Discussions section](https://github.com/znsio/specmatic/discussions/748), is it ok if I close this issue?

**Comment by markgargan** [comment]
@joelrosario Yes absolutely Joel!

**Comment by joelrosario** [comment]
@markgargan I'm closing this issue, and will reply shortly on the discussion thread.
