### ISSUE TITLE
API Coverage Summary missing in the logs after upgrading from specmatic v0.77.0

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#787]
Description:
API Coverage Summary is not shown in the logs since 0.78.0 when there is no specmatic.json file present.

Observation:
The coverage report is shown with specmatic 0.77.0
The coverage report is NOT shown with specmatic 0.78.0+

Setup:
Junit5
Maven - failsafe plugin
Springboot3 - /actuator/mappings endpoint used.
No `specmatic.json` file.

**Comment by jaydeepk** [comment]
@kiranpatel11 , Yes we have modified the implementation of the API Coverage Summary report so that it is generated only if the project has a specmatic.json file.

**Comment by joelrosario** [comment]
Hi @kiranpatel11,

Specmatic now prints the API Coverage Summary report even without a specmatic.json file.

Closing this for now. Please feel free to reopen this issue if you have any followup comments or questions.
