### ISSUE TITLE
Fix .success() method in Results

### ISSUE THREAD

**Issue by joelrosario** [specmatic/specmatic#792]
**Description**
The Results.success() method returns true if there are successes, but does not check that there are no failures

It should return true if successes >1 and failures == 0.

Make sure the tests are passing, and if not please discuss the test failures with us.

**Comment by TejasDhole** [comment]
hey @joelrosario  im intrested contributing in this issue ,and i've also get solution but for me to test the code ,when i try to  ./gradlew clean build
my some test cases are getting failed



```plaintext
Task :application:test
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot lo
BundleCommandTest > the command should compress all stub commands in the config into a zip file() FAILED

BundleCommandTest > should list stub files in subdirectories of the given directory() FAILED

BundleCommandTest > should list stub files in a given directory() FAILED
org.opentest4j.AssertionFailedError at BundleCommandTest.kt:72

BundleCommandTest > should avoid entries that are neither file nor directory() FAILED
java.lang.NullPointerException at BundleCommandTest.kt:120

BundleCommandTestE2E > basic stub bundle command functionality(File) FAILED
java.nio.file.InvalidPathException at BundleCommandTestE2E.kt:131

BundleCommandTestE2E > bundle is generated with shifted base(File) FAILED
java.nio.file.InvalidPathException at BundleCommandTestE2E.kt:164

BundleCommandTestE2E > test bundle is generated(File) FAILED
java.nio.file.InvalidPathException at BundleCommandTestE2E.kt:208

CentralContractRepoReportCommandTestE2E > test generates report json file() FAILED

StubCommandTest > when a contract with the incorrect extension command should exit with non-zero(Path) FAILED

66 tests completed, 9 failed, 1 skipped

Task :application:test FAILED

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':application:test'.
There were failing tests. See the report at: file:///C:/Users/Tejas/Desktop/new%20open/specmatic/application/build/reports/tests/test/index.html

Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

Get more help at https://help.gradle.org/
BUILD FAILED in 1m 15s
30 actionable tasks: 30 executed
```
![Screenshot (127)](https://github.com/znsio/specmatic/assets/98216813/a1bcba8a-bca4-4de3-bfa4-ef17c3f93549)
![Screenshot (128)](https://github.com/znsio/specmatic/assets/98216813/d45f01d4-7c10-478a-b40f-b848e65936bc)
![Screenshot (129)](https://github.com/znsio/specmatic/assets/98216813/564d433e-ae0f-4e86-baea-38187692740e)
![Screenshot (130)](https://github.com/znsio/specmatic/assets/98216813/50853569-e8fb-4691-aee9-4c96b23f8797)

**Comment by harikrishnan83** [comment]
@TejasDhole Thanks for your interest. However without the details as to the changes you made it is hard to guide you on this. Can you please raise a PR with the code changes so that we can take a look and provide some debugging steps? Also if you could look at what is the cause of the failure? cc @joelrosario
