### ISSUE TITLE
name is blank in junit report testcases

### ISSUE THREAD

**Issue by ryan-bennetts** [specmatic/specmatic#798]
**Description**
When generating junit reports the name attribute on the testcases is blank (e.g. `name=""`)

**Steps to reproduce**
1. Create service.yaml file from [Getting started API Specification example](https://specmatic.in/getting_started.html#api-specification)
2. Run `npx specmatic test service.yaml --testBaseURL=https://my-json-server.typicode.com/znsio/specmatic-documentation --junitReportDir .`

**Expected behavior**
Within TEST-junit-jupiter.xml testcases will have populated name attributes (or some way to inform these values)

**System Information:**
 - OS & version: Windows 11
 - Specmatic version: 0.81.0
 - Node version: 18.18.0

**Comment by harikrishnan83** [comment]
@ryan-bennetts Thanks for reporting the issue. We will take a look and get back.

**Comment by joelrosario** [comment]
Hi @ryan-bennetts, you may have already noticed that the test name appears under "display-name". Can you please share why having the name populated is necessary for your use case so that we have some more context about how you are using it?

cc @jaydeepk @harikrishnan83

**Comment by ryan-bennetts** [comment]
Hi @joelrosario - I'm using the test output as input to Azure Pipeline's [Publish Test Results](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2) task. This only includes tests where the name attribute is populated. Currently the Azure Pipelines task shows 0 results in the file because of the missing names.

**Comment by barath121** [comment]
@harikrishnan83 We are also facing a similar issue , When using JUNIT reporter specmatic tests do not have a display name and is dumped as undefined

```
<testsuite name="undefined" errors="0" failures="0" skipped="0" timestamp="2024-01-09T06:02:06" time="22.207" tests="2">
```
