### ISSUE TITLE
How do I add a bearer token to all of tests?

### ISSUE THREAD

**Issue by GregLeung** [specmatic/specmatic#812]
Hi, I read: https://specmatic.in/documentation/specmatic_json.html, knowing that there is a security attribute we can add to add specific header for authentication and authorization, but it didn't show how to add a bearer token to the requests, how to do that? thanks!

**Comment by joelrosario** [comment]
Hi @GregLeung,

We have a sample project [here](https://github.com/znsio/specmatic-order-api-java-with-oauth) that demonstrates how an oauth token can be used to run contract tests when a real oauth provider is involved. Pease have a look at the [README](https://github.com/znsio/specmatic-order-api-java-with-oauth#running-contract-tests) in this project. It has a section called "Running contract tests" that describes how to configure an oauth token in specmatic.json, and how this token is leveraged in the request when tests are run.

Can you tell us more though about how you are running the tests?

**Comment by joelrosario** [comment]
@GregLeung In addition to the examples that I shared, Specmatic now has the ability to read auth tokens from environment variables. You can read more about it [here](https://specmatic.in/documentation/authentication.html).

I am closing this for now, but please us know if you need more help by posting here or opening a new issue.
