### ISSUE TITLE
Request to add features 'only' and 'skip' test case execution

### ISSUE THREAD

**Issue by piyush2206** [specmatic/specmatic#816]
**Is your feature request related to a problem? Please describe.**
Testing framework like jest provide features of [only](https://jestjs.io/docs/api#describeonlyname-fn) and [skip](https://jestjs.io/docs/api#describeskipname-fn). Requesting similar feature is specmatic. This will help in running only selective test cases during development period. 

**Describe the solution you'd like**
Examples names can support like xsuccess and ffailure. 

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by harikrishnan83** [comment]
@piyush2206 Thanks for reaching out.

The capability that you are asking for already exists in Specmatic. Please refer to below [documentation](https://specmatic.in/documentation/contract_tests.html#run-only-passing-tests-in-ci) on `filterName` and `filterNotName`. These arguments can be sent as part of the variable arg parameter for Node and Python wrappers.

Hope this helps. cc @jaydeepk

**Comment by harikrishnan83** [comment]
@piyush2206 can you please check with the latest specmatic-node and specmatic-python wrappers?

## Node
* This will only run path containing `findAvailableProducts`

```javascript
specmatic.testWithApiCoverage(getApp(), APP_HOST, APP_PORT, "", ["--filter-name=/findAvailableProducts"]
```
* And this will run all tests except path containing `findAvailableProducts`

```javascript
specmatic.testWithApiCoverage(getApp(), APP_HOST, APP_PORT, "", ["--filter-not-name=/findAvailableProducts"]
```

## Python
* Here is an example for Flask application

```python
Specmatic() \
    .with_project_root(ROOT_DIR) \
    .with_stub(stub_host, stub_port, [expectation_json_file]) \
    .with_wsgi_app(app, app_host, app_port) \
    .test_with_api_coverage_for_flask_app(TestContract, app, args=["--filter-not-name=/findAvailableProducts"]) \
    .run()
```

Hope this helps. Closing the issue. Please feel free to re-open if you have any questions on this.

**Comment by barath121** [comment]
@harikrishnan83 When i am passing multiple --filter-not-name it gets stuck. How can i filter multiple paths?
