### ISSUE TITLE
Error when using a stub contract which has examples as ref

### ISSUE THREAD

**Issue by piyush2206** [specmatic/specmatic#817]
**Description**
Getting error when using a stub contract which has examples as ref.  

**Steps to reproduce**
1. when refs is added in examples and that contract is used as a stub in other services test
```
examples:
    failure:
        $ref: '#/components/examples/deleteJob500'
```

it throws error when being used as stub where examples should not be an problem

```
 >> RESPONSE.BODY
  
       Contract expected JSON object but stub contained ""
```

**Expected behavior**
The stub must respond with correct data as set in stub json 

**Screenshots**

**System Information:**
 - OS & version: [e.g. MacOS 10.15.7]
 - Browser & version: [e.g. chrome, safari]
 - Specmatic version: [e.g. 0.17.0]
 - JDK version: [e.g. 14]

**Additional context**

**Comment by harikrishnan83** [comment]
hello @piyush2206, the fix for this is part of [release 1.2.4](https://github.com/znsio/specmatic/releases/tag/1.2.4). Kindly check. cc @jaydeepk
