### ISSUE TITLE
A recording with Content-Length in the response shows an error saying "Header named Content-Length in the stub was not in the contract"

### ISSUE THREAD

**Issue by joelrosario** [specmatic/specmatic#860]
**Description**

Bug report from [#852]:
I got an error message that the two recorded files weren't compatible with each other, which was a bit surprising when both were recorded by the same program at the same time.
...stub0.json didn't match ...proxy_generated.yaml
Error from contract ...proxy_generated.yaml

```
 In scenario "GET /getPerson/XMXDX. Response: GET /getPerson/XMXDX"
  API: GET /getPerson/XMXDX -> 200

    >> RESPONSE.HEADERS.Content-Length

       Header named Content-Length in the stub was not in the contract
```

**Steps to reproduce**
1. Run `specmatic proxy --target https://api.thecatapi.com recordings`
2. Run `curl 'http://localhost:9000/v1/images/search?limit=10'`
3. Run `specmatic stub recordings/proxy_generated.yaml`

We'll see this error:
```
    Error from contract recordings/proxy_generated.yaml
  
      In scenario "GET /v1/images/search?limit=10. Response: GET /v1/images/search?limit=10"
      API: GET /v1/images/search -> 200
  
        >> RESPONSE.HEADERS.Content-Length
  
           Header named Content-Length in the stub was not in the contract
```

**Expected behavior**
The command `specmatic stub recordings/proxy_generated.yaml` should just have worked.

**System Information:**
 - OS & version: macOS Sonoma 14.1.2
 - Browser & version: n/a
 - Specmatic version: 1.0.3
 - JDK version: openjdk version "1.8.0_372"

**Additional context**
This issue was filed based on [#852]. This should be automatically fixed when [#859] is resolved.

**Comment by harikrishnan83** [comment]
Fixed as part of [Release 1.2.0](https://github.com/znsio/specmatic/releases/tag/1.2.0)
