### ISSUE TITLE
API Coverage File in a Parsable format.

### ISSUE THREAD

**Issue by barath121** [specmatic/specmatic#908]
**Is your feature request related to a problem? Please describe.**
Get the API coverage in some file like JSON or XML which can be used to enforce rules in Pipeline.

**Describe alternatives you've considered**
Reading the table that is outputted but it is not supported in Azure CI.

**Comment by harikrishnan83** [comment]
hello @barath121, thanks for reaching out.

If your objective is to enforce a certain minimum API coverage percentage and fail the build based on the same, I recommend setting the same in ```specmatic.json``` and Specmatic itself will fail the contract test suite if the criteria is not met. Here is a snippet which is setting the `minThresholdPercentage` to 100.

```json
"report": {
    "formatters": [
      {
        "type": "text",
        "layout": "table"
      }
    ],
    "types": {
      "APICoverage": {
        "OpenAPI": {
          "successCriteria": {
            "minThresholdPercentage": 100,
            "maxMissedEndpointsInSpec": 0,
            "enforce": true
          },
          "excludedEndpoints": [
            "/health"
          ]
        }
      }
    }
  }
```

Here is a short video and detailed reference - [API Coverage Report](https://specmatic.in/updates/detect-mismatches-between-your-api-specifications-and-implementation-specmatic-api-coverage-report/#gsc.tab=0)

However if you do want to parse the API coverage report, we do have a JSON format output now. It should be available under ```build/reports/specmatic/coverage_report.json```. Hope this helps.

**Comment by barath121** [comment]
Hey @harikrishnan83 
The coverage_report.json is not being generated when using with python tested for verison 0.26.6 of Specmatic.

**Comment by harikrishnan83** [comment]
@barath121 thanks for reporting this, I will take a look and get back to you.

**Comment by harikrishnan83** [comment]
@barath121 we ran tests on our [sample project](https://github.com/znsio/specmatic-order-api-python) with latest Specmatic Python release [0.26.7](https://pypi.org/project/specmatic/0.26.7) and the `coverage_report.json` is getting generated under build folder as expected. Can you please check?
