### ISSUE TITLE
Create new version tag 1.2.5 on NPM for specmatic-node 

### ISSUE THREAD

**Issue by piyush2206** [specmatic/specmatic#915]
**Is your feature request related to a problem? Please describe.**
Unable to NPM install new version of specmatic node - 1.2.5

**Describe the solution you'd like**
Create new version on NPM - 1.2.5

**Comment by harikrishnan83** [comment]
hello @piyush2206 , thanks for reporting this. We have released [specmatic node 1.2.5](https://www.npmjs.com/package/specmatic/v/1.2.5).
