### ISSUE TITLE
Support HTTP/S Source Provider

### ISSUE THREAD

**Issue by noelmccrory** [specmatic/specmatic#925]
**Is your feature request related to a problem? Please describe.**
Currently it is only possible use git repos as a provider for sources in `specmatic.json`. In some cases API Specs may already be stored in a web repository which can't be accessed by Specmatic currently.

**Describe the solution you'd like**
Add a `http` provider that will allow you to specify the location of an API spec that is stored on a web server.

**Describe alternatives you've considered**
Alternative would be to migrate all existing API specs to a new git repository.

**Additional context**
N/A

**Comment by harikrishnan83** [comment]
@noelmccrory thanks for reporting this. It is indeed on our list. Will keep you posted.

**Comment by joelrosario** [comment]
Hi @noelmccrory, we've just implemented web sources in Specmatic. You can read about it in our [documentation](https://specmatic.in/documentation/specmatic_json.html#use-specifications-from-the-web). It will be out soon in the next release.
