### ISSUE TITLE
Improve documentation on how response examples are used to validate the contract

### ISSUE THREAD

**Issue by mariusz-mc** [specmatic/specmatic#935]
**Description**
The documentation is not very clear on how the examples from the response are being used.
https://specmatic.in/documentation/contract_tests.html#specmatic-contract-test---command-line
It does say only `Specmatic is able to correlate the request and response examples based on naming convention` but it does not explain what the correlation realy does.

The examples, could make one to assume that the response from example section is actually verified with the real response from the server. However, the correlation does check **only the HTTP code.** 

I think there should be a clear information the response data for the examples are not being validated as part of contract tests.

I can understand the intention for this behaviour as contract tests should not test the business logic,  however the provided examples in the documentation may suggest something different.

There is some vague explantion in the .spec section saying
`. Please note that Specmatic validates your examples for datatype correctness against the specification. ` 
but I think it's not enouh clear in general.

**Comment by harikrishnan83** [comment]
@mariusz-mc Thanks for your feedback on the documentation. We will update it for improving the clarity.

**Comment by joelrosario** [comment]
Hi @mariusz-mc thanks for highlight this point! We have updated our [documentation](https://specmatic.in/documentation/contract_tests.html#how-the-contract-test-works-step-by-step) to explain how response examples are used. We have also called out how contract tests (the tests that Specmatic runs) are different from API tests.
