### ISSUE TITLE
Docker image latest tag is missing

### ISSUE THREAD

**Issue by tkrisztian95** [specmatic/specmatic#942]
**Is your feature request related to a problem? Please describe.**
I would like to always fetch the latest Specmatic Docker image from Hub. But, there is no tag `latest`.

**Describe the solution you'd like**
Are you considering adding a moving tag `latest`, point to the image with the current Specmatic version tag?

**Comment by harikrishnan83** [comment]
@tkrisztian95 Thanks for bringing this up. We have done this. Release ```1.2.14``` is available with its version number as well as ```latest``` tag. Please see [Docker Hub Specmatic tags page](https://hub.docker.com/r/znsio/specmatic/tags) and let us know if you have any questions.

**Comment by tkrisztian95** [comment]
Amazing! Thanks a lot! 🚀
