### ISSUE TITLE
Getting Error -> Error: Java heap space\n'

### ISSUE THREAD

**Issue by shubhamsinghalfynd** [specmatic/specmatic#972]
**Description**

**Steps to reproduce**
1. Create a file ...
2. Run this command: ...
3. Make an http request looking like this: ...

**Expected behavior**

**Screenshots**

**System Information:**
 - OS & version: [e.g. MacOS 10.15.7]
 - Browser & version: [e.g. chrome, safari]
 - Specmatic version: [e.g. 0.17.0]
 - JDK version: [e.g. 14]

**Additional context**

**Comment by jaydeepk** [comment]
Thanks for reporting this @shubhamsinghalfynd .
Could you please let us know which version of the Specmatic Python are you using?

**Comment by barath121** [comment]
@jaydeepk - 0.26.3

**Comment by barath121** [comment]
@jaydeepk Any updates?

**Comment by harikrishnan83** [comment]
@barath121 as discussed, kindly request @shubhamsinghalfynd to raise a fresh issue with detail as per template.
