### ISSUE TITLE
Support for File Path Resolution in $ref Property in Specmatic

### ISSUE THREAD

**Issue by pooransuthar1999** [specmatic/specmatic#998]
Problem Statement:- As we have a micro-service architecture there are multiple services with multiple features so most of the schema that we are writing is somewhere or another way the same instead of rewriting the same schema twice we were creating a common folder where all the common schema's or examples will be written and we can pass the file path of that schema to avoid multiple writes. The spectral extension does resolve the file path when added in API-specification so we were expecting the same in specmatic.
Solution expectation:-
Let's say i have created a file called UserSchemaCmn.yaml and inside that I wrote my schema
```

- `type: object
- properties:
-   application_id:
-     type: string
-   user_id:
-     type: string
-   password_last_modified:
-     type: string`

```
Then in the other file i can access it just by providing the path in $ref example:- 

- `    UserSchemaCmn:
-       $ref: "../../../../common/openapi/schemas/UserSchemaCmn.yaml" `

**Comment by harikrishnan83** [comment]
Thanks @pooransuthar1999 for reporting the issue. We are looking into it.

**Comment by joelrosario** [comment]
Hi @pooransuthar1999, thanks for getting in touch. Specmatic supports referring to externalised schemas. You may want to double check that the included file being referred to contains the following structure:

```yaml
components:
  schemas:
    YourComponentName:
      type: object
```

And you can reference it from another schema using this syntax:

```yaml
$ref: "common.yaml#/components/schemas/YourComponentName"
```
